// FE-1A OpenAPI type generation (docs/design/FRONTEND-MIGRATION-PLAN.md §1).
// Reads the committed contract document api/openapi/openapi.json (ADR-0018)
// and emits frontend/src/api/types.gen.ts. Fully offline and deterministic:
// same input bytes => same output bytes. Never hand-edit the output — the
// drift gate (frontend/scripts/verify.sh) regenerates and byte-compares.
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const specPath = fileURLToPath(
  new URL("../../../api/openapi/openapi.json", import.meta.url),
);
const outPath = fileURLToPath(
  new URL("../../src/api/types.gen.ts", import.meta.url),
);

const specBytes = readFileSync(specPath);
const specHash = createHash("sha256").update(specBytes).digest("hex");
const generatorVersion = JSON.parse(
  readFileSync(
    fileURLToPath(
      new URL("./node_modules/openapi-typescript/package.json", import.meta.url),
    ),
    "utf8",
  ),
).version;

const ast = await openapiTS(JSON.parse(specBytes.toString("utf8")));
const body = astToString(ast);

const header = `// Code generated by openapi-typescript v${generatorVersion} — DO NOT EDIT.
//
// Source:  api/openapi/openapi.json (sha256:${specHash})
// Command: npm run generate   (frontend/scripts/generate-types.sh)
//
// This file is drift-gated: CI regenerates it from the committed OpenAPI
// document and fails on any byte difference. Hand edits cannot land.
// Generated types are compile-time only — runtime trust requires the
// decoder boundary (docs/design/FRONTEND-SECURITY-CONTRACT.md §7).

`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, header + body);
process.stdout.write(
  `generated src/api/types.gen.ts from openapi.json (sha256:${specHash.slice(0, 16)}…) with openapi-typescript v${generatorVersion}\n`,
);
