package main

// ─── One-Click Node Bootstrap ──────────────────────────────────────────────
//
// Serves a shell script and docker-compose.yml that fully automate DP node
// deployment. The admin generates an enrollment token in the GUI; the GUI
// shows a single curl|bash command. On the target server, the script:
//
//  1. Installs Docker Engine + Compose plugin if missing
//  2. Creates a working directory (/opt/culvert-dp)
//  3. Downloads docker-compose.yml from the CP (pre-configured)
//  4. Runs docker compose up -d
//  5. The DP container enrolls with the CP automatically on first boot
//

import (
	"encoding/json"
	"fmt"
	"net"
	"net/http"
	"os"
	"strings"
	"text/template"
)

// defaultImage is the default container image; overridden by registry settings.
const defaultImage = "ghcr.io/kidcarmi/culvert"

// bootstrapImage returns the image reference for DP nodes, checking registry
// settings first, falling back to the default ghcr.io image with current version.
func bootstrapImage() string {
	data, err := os.ReadFile(registrySettingsFile)
	if err == nil && len(data) > 0 {
		var s map[string]string
		if json.Unmarshal(data, &s) == nil && s["registry_url"] != "" {
			img := s["registry_url"]
			if version != "dev" {
				img += ":" + version
			} else {
				img += ":latest"
			}
			return img
		}
	}
	if version != "dev" {
		return defaultImage + ":" + version
	}
	return defaultImage + ":latest"
}

// updaterImage returns the updater sidecar image reference.
func updaterImage() string {
	data, err := os.ReadFile(registrySettingsFile)
	if err == nil && len(data) > 0 {
		var s map[string]string
		if json.Unmarshal(data, &s) == nil && s["registry_url"] != "" {
			base := s["registry_url"]
			// Derive updater image: append -updater to the base name
			if version != "dev" {
				return base + "-updater:" + version
			}
			return base + "-updater:latest"
		}
	}
	base := defaultImage + "-updater"
	if version != "dev" {
		return base + ":" + version
	}
	return base + ":latest"
}

// ── Bootstrap shell script ─────────────────────────────────────────────────

var bootstrapScriptTmpl = template.Must(template.New("bootstrap").Parse(`#!/bin/bash
# ─── Culvert Data Plane Bootstrap ────────────────────────────────────────
# Generated by Control Plane at {{.CPHost}}
# This script installs Docker (if needed) and starts a Culvert DP node.
set -euo pipefail

COMPOSE_DIR="/opt/culvert-dp"
CP_BASE="{{.CPBase}}"
TOKEN_PATH="{{.TokenPath}}"

echo "╔══════════════════════════════════════════╗"
echo "║   Culvert Data Plane Bootstrap           ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# ── 1. Install Docker if not present ────────────────────────────────────
install_docker() {
  echo "[1/4] Checking Docker installation..."
  if command -v docker &>/dev/null; then
    echo "  ✓ Docker already installed: $(docker --version)"
  else
    echo "  → Installing Docker Engine..."
    if [ -f /etc/os-release ]; then
      . /etc/os-release
      case "$ID" in
        ubuntu|debian)
          apt-get update -qq
          apt-get install -y -qq ca-certificates curl gnupg lsb-release
          install -m 0755 -d /etc/apt/keyrings
          curl -fsSL "https://download.docker.com/linux/$ID/gpg" | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          chmod a+r /etc/apt/keyrings/docker.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/$ID $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
          apt-get update -qq
          apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
          ;;
        centos|rhel|rocky|alma|fedora)
          dnf install -y dnf-plugins-core || yum install -y yum-utils
          dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo 2>/dev/null || \
            yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          dnf install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin 2>/dev/null || \
            yum install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
          ;;
        amzn)
          yum install -y docker
          # Amazon Linux uses older docker; install compose plugin separately
          mkdir -p /usr/local/lib/docker/cli-plugins
          COMPOSE_VER=$(curl -fsSL https://api.github.com/repos/docker/compose/releases/latest | grep '"tag_name"' | head -1 | cut -d'"' -f4)
          curl -fsSL "https://github.com/docker/compose/releases/download/${COMPOSE_VER}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/lib/docker/cli-plugins/docker-compose
          chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
          ;;
        *)
          echo "  ✗ Unsupported distro: $ID. Install Docker manually: https://docs.docker.com/engine/install/"
          exit 1
          ;;
      esac
    else
      echo "  ✗ Cannot detect OS. Install Docker manually: https://docs.docker.com/engine/install/"
      exit 1
    fi
    systemctl enable --now docker
    echo "  ✓ Docker installed: $(docker --version)"
  fi

  # Verify compose plugin
  if ! docker compose version &>/dev/null; then
    echo "  ✗ Docker Compose plugin not found. Install it: https://docs.docker.com/compose/install/"
    exit 1
  fi
  echo "  ✓ Docker Compose: $(docker compose version --short)"
}

# ── 2. Create working directory ─────────────────────────────────────────
setup_dir() {
  echo ""
  echo "[2/4] Setting up $COMPOSE_DIR..."
  mkdir -p "$COMPOSE_DIR"
  cd "$COMPOSE_DIR"
  echo "  ✓ Working directory ready"
}

# ── 3. Download docker-compose.yml from Control Plane ───────────────────
download_compose() {
  echo ""
  echo "[3/4] Downloading docker-compose.yml from Control Plane..."
  curl -fsSL -k "${CP_BASE}/api/cluster/bootstrap/${TOKEN_PATH}/compose" -o docker-compose.yml
  echo "  ✓ docker-compose.yml downloaded"
}

# ── 4. Start DP node ────────────────────────────────────────────────────
start_dp() {
  echo ""
  echo "[4/4] Starting Culvert Data Plane..."
  docker compose up -d
  echo ""
  echo "  ✓ Data Plane node started!"
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  The DP node is enrolling with the Control Plane."
  echo "  Check status:  cd $COMPOSE_DIR && docker compose logs -f dp"
  echo "  Stop:          cd $COMPOSE_DIR && docker compose down"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
}

# ── Run ─────────────────────────────────────────────────────────────────
install_docker
setup_dir
download_compose
start_dp
`))

// ── Docker Compose template for DP ─────────────────────────────────────

var bootstrapComposeTmpl = template.Must(template.New("compose").Parse(`# Culvert Data Plane — generated by Control Plane
# DO NOT EDIT — managed by the Culvert cluster system
#
# To update: use the Updates panel in the Control Plane GUI
# To stop:   docker compose down
# To logs:   docker compose logs -f dp

services:
  dp:
    image: {{.Image}}
    container_name: culvert-dp
    restart: unless-stopped
    depends_on:
      dp-updater:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "1080:1080"
    volumes:
      - dp-data:/data
    environment:
      - TZ=UTC
      - ENROLL_URL={{.EnrollURL}}
    command: >
      sh -c '
        ARGS="-port 8080
          -ca-path /data/ca.bundle
          -blocklist /data/blocklist.txt
          -policy /data/policy.json
          -logfile /data/proxy.log
          -audit-log /data/audit.jsonl
          -geoip-db /app/GeoLite2-Country.mmdb
          -yara-rules-dir /app/yara
          -threat-feed-db /data/threatfeeds.json
          -fileprofiles-file /data/fileprofiles.json
          -updater-url http://dp-updater:7123"

        if [ -n "$$ENROLL_URL" ]; then
          ARGS="$$ARGS --enroll $$ENROLL_URL"
        fi

        exec ./culvert $$ARGS
      '
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  dp-updater:
    image: {{.UpdaterImage}}
    container_name: culvert-dp-updater
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - dp-data:/data:ro
    ports:
      - "7123:7123"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:7123/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  dp-data:
`))

// ── HTTP handlers ──────────────────────────────────────────────────────

// apiBootstrapRouter routes bootstrap requests to either the shell script
// or the docker-compose.yml handler based on the path suffix.
func apiBootstrapRouter(w http.ResponseWriter, r *http.Request) {
	if strings.HasSuffix(r.URL.Path, "/compose") {
		apiBootstrapCompose(w, r)
	} else {
		apiBootstrapScript(w, r)
	}
}

// apiBootstrapScript serves the install script for a given enrollment token.
// GET /api/cluster/bootstrap/{token} — returns shell script (no auth required,
// but the token itself is the auth — it's single-use and time-limited).
func apiBootstrapScript(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	token := extractBootstrapToken(r.URL.Path, "/api/cluster/bootstrap/")
	if token == "" || strings.Contains(token, "/") {
		http.Error(w, "invalid token path", http.StatusBadRequest)
		return
	}

	// Verify token exists (don't consume it — compose download needs it too).
	if !globalClusterStore.TokenExists(token) {
		http.Error(w, "invalid or expired token", http.StatusNotFound)
		return
	}

	// Derive CP base URL from request.
	cpBase := cpBaseURL(r)

	w.Header().Set("Content-Type", "text/x-shellscript; charset=utf-8")
	w.Header().Set("Content-Disposition", "inline; filename=culvert-bootstrap.sh")
	err := bootstrapScriptTmpl.Execute(w, map[string]string{
		"CPHost":    r.Host,
		"CPBase":    cpBase,
		"TokenPath": token,
	})
	if err != nil {
		logger.Printf("Bootstrap: script template error: %v", err)
	}
}

// apiBootstrapCompose serves the docker-compose.yml for a given enrollment token.
// GET /api/cluster/bootstrap/{token}/compose — returns YAML (no auth required,
// token is the auth).
func apiBootstrapCompose(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	// Extract token — path is /api/cluster/bootstrap/{token}/compose
	path := r.URL.Path
	const prefix = "/api/cluster/bootstrap/"
	const suffix = "/compose"
	if !strings.HasPrefix(path, prefix) || !strings.HasSuffix(path, suffix) {
		http.Error(w, "invalid path", http.StatusBadRequest)
		return
	}
	token := path[len(prefix) : len(path)-len(suffix)]
	if token == "" || strings.Contains(token, "/") {
		http.Error(w, "invalid token", http.StatusBadRequest)
		return
	}

	// Verify token exists (don't consume — enrollment RPC consumes it).
	if !globalClusterStore.TokenExists(token) {
		http.Error(w, "invalid or expired token", http.StatusNotFound)
		return
	}

	// Build enrollment URL — derive CP host from the HTTP request so the
	// generated docker-compose.yml works from remote machines (not just localhost).
	cpAddr := enrollmentCPAddr(r, clusterRole.grpcAddr)
	caFP := globalClusterCA.CACertFingerprint()
	enrollURL := fmt.Sprintf("culvert://enroll/%s/%s?ca-fp=sha256:%s", cpAddr, token, caFP)

	w.Header().Set("Content-Type", "application/x-yaml; charset=utf-8")
	w.Header().Set("Content-Disposition", "inline; filename=docker-compose.yml")
	err := bootstrapComposeTmpl.Execute(w, map[string]string{
		"Image":        bootstrapImage(),
		"UpdaterImage": updaterImage(),
		"EnrollURL":    enrollURL,
	})
	if err != nil {
		logger.Printf("Bootstrap: compose template error: %v", err)
	}
}

// ── Helpers ────────────────────────────────────────────────────────────

// extractBootstrapToken extracts the token segment from a bootstrap URL path.
// For /api/cluster/bootstrap/abc123 → "abc123"
// For /api/cluster/bootstrap/abc123/compose → "abc123"
func extractBootstrapToken(path, prefix string) string {
	if !strings.HasPrefix(path, prefix) {
		return ""
	}
	rest := path[len(prefix):]
	// Strip trailing /compose if present
	rest = strings.TrimSuffix(rest, "/compose")
	// Must be a single segment (no slashes)
	if strings.Contains(rest, "/") {
		return ""
	}
	return rest
}

// cpBaseURL derives the CP's external base URL from the incoming request.
func cpBaseURL(r *http.Request) string {
	scheme := "https"
	if r.TLS == nil {
		scheme = "http"
	}
	host := r.Host
	if trustForwardedHeaders {
		if fp := r.Header.Get("X-Forwarded-Proto"); fp == "http" || fp == "https" {
			scheme = fp
		}
		if fh := r.Header.Get("X-Forwarded-Host"); fh != "" {
			host = fh
		}
	}
	return scheme + "://" + host
}

// enrollmentCPAddr derives the gRPC Control Plane address for the enrollment URL.
// Uses the HTTP request's host (the IP/hostname the admin used to access the UI)
// combined with the gRPC port from the configured listen address.
// IPv6-safe: strips brackets before net.JoinHostPort to prevent double-bracketing.
func enrollmentCPAddr(r *http.Request, grpcListenAddr string) string {
	// If grpcAddr already contains a routable host (not just :port), use it as-is.
	if grpcListenAddr != "" {
		gHost, _, err := net.SplitHostPort(grpcListenAddr)
		if err == nil && gHost != "" && gHost != "0.0.0.0" && gHost != "::" {
			return grpcListenAddr
		}
	}

	// Derive host from the HTTP request.
	cpHost := r.Host
	if trustForwardedHeaders {
		if fh := r.Header.Get("X-Forwarded-Host"); fh != "" {
			cpHost = fh
		}
	}

	// Extract host — IPv6-safe (r.Host for IPv6 is [::1]:port).
	host, _, err := net.SplitHostPort(cpHost)
	if err != nil {
		// No port or bare host — strip brackets to prevent [[::1]]:port
		host = strings.Trim(cpHost, "[]")
	}

	// Extract gRPC port from the listen address.
	_, grpcPort, err := net.SplitHostPort(grpcListenAddr)
	if err != nil || grpcPort == "" {
		grpcPort = "50051"
	}

	// net.JoinHostPort adds brackets for IPv6 automatically.
	return net.JoinHostPort(host, grpcPort)
}

