package main

// STRUCTURAL WALL for the policy-decision lines.
//
// The four emitters no longer hand their values to fmt; they append them into
// a builder. That removes the single call site where every interpolated value
// was visible at a glance, so the CWE-117 question — "can a client-chosen byte
// reach the process log unsanitised?" — is now answered across a dozen small
// append calls instead of one format string.
//
// This gate answers it mechanically, and it is deliberately STRUCTURAL rather
// than behavioural. A behavioural test can only prove the values it thinks to
// pass; it cannot notice that someone added a thirteenth append carrying a
// header value. The rule below holds for every value in every branch, whether
// a test exercises it or not.
//
// THE RULE. Inside logPolicyAllow / Block / Drop / Redirect, every string that
// is appended to the line must be one of:
//
//   - a string literal (the fixed template text the emitter owns),
//   - a call to sanitizeLog(...),
//   - a local bound to a sanitizeLog(...) result, or
//   - one of the three values in policyLineSafeBare, each of which is named
//     there with the reason it cannot carry client-chosen bytes.
//
// Anything else fails, and the right fix is almost always sanitizeLog — not an
// addition to the safe-bare list. Widening that list is a security decision and
// must come with the argument for why the bytes cannot be attacker-chosen, the
// way the three entries already there do.
//
// This is the same wall, and the same lesson, as
// TestSOCKS5_EveryDestinationLogSiteSanitises: sanitising one argument of a
// call does not sanitise the call, and walling one call shape does not wall the
// path.

import (
	"go/ast"
	"go/parser"
	"go/token"
	"strings"
	"testing"
)

// policyLineSafeBare are the values a decision line may carry WITHOUT
// sanitizeLog, each with the reason it cannot carry client-chosen bytes.
//
// These are exactly the values the pre-change format strings interpolated with
// a bare %s, so the wall encodes the contract that already held; it does not
// relax it.
var policyLineSafeBare = map[string]string{
	// net.SplitHostPort of r.RemoteAddr, which net/http fills from the
	// accepted socket. Kernel-supplied, never client-chosen.
	"clientIP": "kernel-supplied peer address",
	// net/http rejects control characters in the request-line method token
	// before a handler ever sees it (pinned by
	// TestHTTPHostHeader_RejectsMostControlCharacters in the SOCKS5 suite).
	"method": "net/http-validated request method token",
	// setupRequestTracing sanitises a client-supplied X-Request-ID inline at
	// the read site and otherwise generates it from the CSPRNG.
	"reqID": "sanitised or generated by setupRequestTracing",
}

// policyLineEmitters are the functions this wall reads.
var policyLineEmitters = []string{
	"logPolicyAllow", "logPolicyBlock", "logPolicyDrop", "logPolicyRedirect",
}

// policyLineAppendCalls are the calls that put bytes into a decision line. A
// new one added without being listed here would escape the wall, which is why
// TestPolicyLine_WallCoversEveryAppendCall checks the inventory separately.
var policyLineAppendCalls = map[string]bool{
	"WriteString": true, "WriteByte": true, "Write": true,
	"writeQuoted": true, "writeInt": true,
	"policyLineHead": true, "policyLineTail": true,
	"emitPolicyLine": true, "growPolicyLine": true,
}

// policyLineReadCalls take nothing INTO the line; they read what is already
// there. They are listed so the inventory control can tell "a call the wall
// understands and need not inspect" from "a call nobody has classified", which
// is the case that must fail.
var policyLineReadCalls = map[string]bool{
	// (*strings.Builder).String — hands the assembled line to emitPolicyLine.
	// Every byte in it was already checked on the way in.
	"String": true,
}

func parsePolicyEmitters(t *testing.T) (fset *token.FileSet, emitters map[string]*ast.FuncDecl) {
	t.Helper()
	fset = token.NewFileSet()
	file, err := parser.ParseFile(fset, "proxy.go", nil, parser.ParseComments)
	if err != nil {
		t.Fatalf("parse proxy.go: %v", err)
	}
	found := map[string]*ast.FuncDecl{}
	ast.Inspect(file, func(n ast.Node) bool {
		d, ok := n.(*ast.FuncDecl)
		if !ok {
			return true
		}
		for _, name := range policyLineEmitters {
			if d.Name.Name == name {
				found[name] = d
			}
		}
		return true
	})
	for _, name := range policyLineEmitters {
		if found[name] == nil {
			t.Fatalf("%s not found in proxy.go — this wall must be re-aimed, not deleted", name)
		}
	}
	return fset, found
}

// sanitisedLocals returns the local variables in fn that are bound to a
// sanitizeLog(...) result, so `safeHost := sanitizeLog(host)` counts as
// sanitised wherever safeHost is later appended.
func sanitisedLocals(fn *ast.FuncDecl) map[string]bool {
	safe := map[string]bool{}
	ast.Inspect(fn.Body, func(n ast.Node) bool {
		as, ok := n.(*ast.AssignStmt)
		if !ok {
			return true
		}
		// Handles both `a := sanitizeLog(x)` and the multi-value
		// `a, b := sanitizeLog(x), sanitizeLog(y)` form the emitters use.
		if len(as.Lhs) == len(as.Rhs) {
			for i, rhs := range as.Rhs {
				if isSanitizeLogCall(rhs) {
					if id, ok := as.Lhs[i].(*ast.Ident); ok {
						safe[id.Name] = true
					}
				}
			}
		}
		return true
	})
	return safe
}

func isSanitizeLogCall(e ast.Expr) bool {
	call, ok := e.(*ast.CallExpr)
	if !ok {
		return false
	}
	id, ok := call.Fun.(*ast.Ident)
	return ok && id.Name == "sanitizeLog"
}

// appendCallName returns the name of the append-style call e represents, and
// whether it is one.
func appendCallName(call *ast.CallExpr) (string, bool) {
	switch fn := call.Fun.(type) {
	case *ast.Ident:
		return fn.Name, policyLineAppendCalls[fn.Name]
	case *ast.SelectorExpr:
		return fn.Sel.Name, policyLineAppendCalls[fn.Sel.Name]
	}
	return "", false
}

// classifyAppendedArg checks ONE argument of one append-style call.
//
// Split out of the wall itself so the rule is readable as a list of the shapes
// an appended value is allowed to take, rather than as a nest of type switches
// inside two ast.Inspect closures.
func classifyAppendedArg(t *testing.T, fset *token.FileSet, emitter, callee string, call *ast.CallExpr, arg ast.Expr, safe map[string]bool) {
	t.Helper()
	switch a := arg.(type) {
	case *ast.BasicLit:
		// A literal is the emitter's own template text.
	case *ast.UnaryExpr:
		// &b — the builder being threaded through.
	case *ast.Ident:
		switch {
		case safe[a.Name]:
		case policyLineSafeBare[a.Name] != "":
		case a.Name == "b" || a.Name == "priority":
			// The builder itself, and the one non-string value a line carries.
		default:
			t.Errorf("%s at %s: %s(%s) appends %q, which is neither sanitizeLog'd nor "+
				"listed in policyLineSafeBare. A client-chosen byte reaching the process "+
				"log forges records (CWE-117). Wrap it in sanitizeLog, or add it to "+
				"policyLineSafeBare WITH the reason it cannot be client-chosen.",
				emitter, fset.Position(call.Pos()), callee, a.Name, a.Name)
		}
	case *ast.CallExpr:
		if isSanitizeLogCall(a) {
			return
		}
		// b.String() feeding emitPolicyLine is the assembled line; every byte
		// in it was already checked on the way in.
		if sel, ok := a.Fun.(*ast.SelectorExpr); ok && policyLineReadCalls[sel.Sel.Name] {
			return
		}
		t.Errorf("%s at %s: %s appends the result of a call that is not sanitizeLog; "+
			"if it can carry client-chosen bytes it must be sanitised.",
			emitter, fset.Position(call.Pos()), callee)
	default:
		t.Errorf("%s at %s: %s appends an expression the wall cannot classify (%T). "+
			"Either simplify it or teach the wall about it deliberately.",
			emitter, fset.Position(call.Pos()), callee, arg)
	}
}

// TestPolicyLine_EveryAppendedValueIsSanitised is the wall itself.
func TestPolicyLine_EveryAppendedValueIsSanitised(t *testing.T) {
	fset, emitters := parsePolicyEmitters(t)

	checked := 0
	for _, name := range policyLineEmitters {
		fn := emitters[name]
		safe := sanitisedLocals(fn)
		ast.Inspect(fn.Body, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}
			callee, isAppend := appendCallName(call)
			if !isAppend {
				return true
			}
			for _, arg := range call.Args {
				checked++
				classifyAppendedArg(t, fset, name, callee, call, arg, safe)
			}
			return true
		})
	}

	// A selector typo that matched nothing would let this wall pass forever.
	if checked < 30 {
		t.Fatalf("the wall inspected only %d appended values across the four emitters; "+
			"it is no longer finding them", checked)
	}
}

// TestPolicyLine_WallCoversEveryAppendCall is the CONTROL for the wall.
//
// The wall only inspects calls it recognises as appending, so a new helper —
// say writeHeaderValue — would carry values into the line WITHOUT being
// checked, and the wall would stay green while the hole opened. This pins the
// inverse: every call an emitter makes, other than the sanitiser itself, must
// be one the wall knows how to inspect.
func TestPolicyLine_WallCoversEveryAppendCall(t *testing.T) {
	fset, emitters := parsePolicyEmitters(t)
	for _, name := range policyLineEmitters {
		ast.Inspect(emitters[name].Body, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}
			if isSanitizeLogCall(call) {
				return true
			}
			callee, isAppend := appendCallName(call)
			if isAppend || policyLineReadCalls[callee] {
				return true
			}
			if callee == "" {
				callee = "<unnamed>"
			}
			t.Errorf("%s at %s calls %q, which the sanitisation wall does not inspect. Any call "+
				"that can put bytes into a decision line must be listed in policyLineAppendCalls "+
				"so TestPolicyLine_EveryAppendedValueIsSanitised checks its arguments.",
				name, fset.Position(call.Pos()), callee)
			return true
		})
	}
}

// TestPolicyLine_SafeBareValuesAreDocumented keeps the safe-bare list honest:
// an entry with an empty reason is an entry nobody argued for.
func TestPolicyLine_SafeBareValuesAreDocumented(t *testing.T) {
	for name, reason := range policyLineSafeBare {
		if strings.TrimSpace(reason) == "" {
			t.Errorf("policyLineSafeBare[%q] has no recorded reason; a value is exempt from "+
				"sanitisation only with the argument for why it cannot be client-chosen", name)
		}
	}
}
