package main

// saas_feed_f3b3_testkit_test.go — shared F3b-3 (activation/recovery/GC) test harness.
//
// It persists REAL committed generations on disk via the F3b-2 generation store (using
// the shared faithful fake verifier's real generated bytes), and wires an activation
// coordinator + GC collector over injectable seams so the commit ordering, recovery
// precedence, override coordination, and GC safety can be proven deterministically. No
// network, no scheduler, no production trust root.

import (
	"bytes"
	"context"
	"sync"
	"testing"
	"time"

	"github.com/KidCarmi/Culvert/internal/catoverride"
	"github.com/KidCarmi/Culvert/internal/saasfeed"
	"github.com/KidCarmi/Culvert/internal/urlcatfeed"
)

// f3b3Now is a fixed clock inside the default generation's validity window (gen
// 2026-07-31, +14d expiry): well after generated_at, well before expiry.
func f3b3Now() time.Time { return time.Date(2026, 8, 1, 0, 0, 0, 0, time.UTC) }

// persistRealGen writes a fully-committed immutable generation for g into genRoot (via the
// real F3b-2 store), with the correct normalized snapshot derived from the verified
// artifact — so the F3b-3 offline re-verify accepts it.
func persistRealGen(t *testing.T, genRoot string, g feedGen) {
	t.Helper()
	snap, err := normalizedSnapshotBytes(&g.Artifact)
	if err != nil {
		t.Fatalf("derive snapshot: %v", err)
	}
	cand := generationCandidate{
		FeedVersion:    g.Manifest.FeedVersion,
		GenerationID:   feedVersionID(g.Manifest.FeedVersion),
		GeneratedAt:    g.Manifest.GeneratedAt,
		ExpiresAt:      g.Manifest.ExpiresAt,
		ManifestSHA256: sha256Hex(g.EnvelopeBytes),
		ArtifactSHA256: g.Manifest.ArtifactSHA256,
		ArtifactSize:   g.Manifest.ArtifactSize,
		CategoryCount:  g.Manifest.CategoryCount,
		HostCount:      g.Manifest.HostCount,
		EnvelopeBytes:  g.EnvelopeBytes,
		ArtifactBytes:  g.ArtifactBytes,
		BundleBytes:    g.BundleBytes,
		SnapshotBytes:  snap,
	}
	store, err := newGenerationStore(genRoot)
	if err != nil {
		t.Fatalf("newGenerationStore: %v", err)
	}
	if _, err := store.Persist(context.Background(), cand); err != nil {
		t.Fatalf("persist generation v%d: %v", g.Manifest.FeedVersion, err)
	}
}

// ─── fake override provider ─────────────────────────────────────────────────────────

// fakeOverrideProvider models the authoritative override source with a controllable
// revision (for the config-churn/race tests). onCurrent runs on every Current() call so a
// test can mutate the revision between build and cutover.
type fakeOverrideProvider struct {
	mu        sync.Mutex
	ov        catoverride.Overrides
	rev       string
	err       error
	calls     int
	onCurrent func(p *fakeOverrideProvider)
}

func newOverrideProvider(rev string) *fakeOverrideProvider {
	return &fakeOverrideProvider{rev: rev}
}

func (p *fakeOverrideProvider) Current() (catoverride.Overrides, string, error) {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.calls++
	if p.onCurrent != nil {
		p.onCurrent(p)
	}
	if p.err != nil {
		return catoverride.Overrides{}, "", p.err
	}
	return p.ov, p.rev, nil
}

func (p *fakeOverrideProvider) set(ov catoverride.Overrides, rev string) {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.ov, p.rev = ov, rev
}

// ─── coordinator builder ────────────────────────────────────────────────────────────

// f3b3Env bundles the coordinator + its stores/holder for a test.
type f3b3Env struct {
	dir       string
	genRoot   string
	floor     *floorStore
	activ     *activationStore
	live      *feedLiveStore
	overrides *fakeOverrideProvider
	coord     *activationCoordinator
	verifier  feedVerifier
}

// coordOpts configures the coordinator wiring (nil seams default to real/os).
type coordOpts struct {
	floorSeam  *floorFS       // floor + activation durability seam (nil ⇒ osFloorFS)
	read       reverifyReader // generation reader (nil ⇒ osReverifyReader)
	verifier   feedVerifier   // nil ⇒ a fresh fake bound to g
	now        func() time.Time
	checkpoint *int64 // nil ⇒ compiledMinFeedVersion (0)
	overrides  *fakeOverrideProvider
}

// newCoordEnv builds a coordinator whose floor/activation live under dir and whose
// generations live under genRoot=dir/generations. g's verifier is used unless overridden.
func newCoordEnv(t *testing.T, dir string, g feedGen, opts coordOpts) *f3b3Env {
	t.Helper()
	genRoot := dir + "/generations"
	seam := osFloorFS()
	if opts.floorSeam != nil {
		seam = *opts.floorSeam
	}
	checkpoint := compiledMinFeedVersion
	if opts.checkpoint != nil {
		checkpoint = *opts.checkpoint
	}
	floor, err := newFloorStoreFS(seam, dir, checkpoint)
	if err != nil {
		t.Fatalf("newFloorStoreFS: %v", err)
	}
	activ, err := newActivationStoreFS(seam, dir)
	if err != nil {
		t.Fatalf("newActivationStoreFS: %v", err)
	}
	verifier := opts.verifier
	if verifier == nil {
		verifier = newFakeVerifier(g)
	}
	read := opts.read
	if read == nil {
		read = osReverifyReader
	}
	now := opts.now
	if now == nil {
		now = f3b3Now
	}
	ov := opts.overrides
	if ov == nil {
		ov = newOverrideProvider("rev-1")
	}
	live := newFeedLiveStore()
	coord := newActivationCoordinator(genRoot, floor, activ, verifier, live, ov, read, checkpoint, now, 0)
	return &f3b3Env{
		dir: dir, genRoot: genRoot, floor: floor, activ: activ, live: live,
		overrides: ov, coord: coord, verifier: verifier,
	}
}

// resetOwnership clears the process-global single-writer flag between tests (it is a
// package-level atomic the coordinator sets on activation).
func resetOwnership(t *testing.T) {
	t.Helper()
	setSignedFeedOwnsLiveStore(false)
	t.Cleanup(func() { setSignedFeedOwnsLiveStore(false) })
}

// multiFakeVerifier dispatches VerifyEnvelope/VerifyArtifact across several generations by
// matching the exact wire bytes — so a coordinator can activate v1, v2, … in one test.
type multiFakeVerifier struct {
	gens []feedGen
}

func multiVerifier(gens ...feedGen) *multiFakeVerifier { return &multiFakeVerifier{gens: gens} }

func (m *multiFakeVerifier) VerifyEnvelope(b []byte) (*urlcatfeed.ManifestPayload, error) {
	for i := range m.gens {
		if bytes.Equal(b, m.gens[i].EnvelopeBytes) {
			mp := m.gens[i].Manifest
			return &mp, nil
		}
	}
	return nil, urlcatfeed.ErrVerify
}

func (m *multiFakeVerifier) VerifyArtifact(artifact, bundle []byte, manifest *urlcatfeed.ManifestPayload) (*urlcatfeed.ArtifactPayload, error) {
	for i := range m.gens {
		if !bytes.Equal(artifact, m.gens[i].ArtifactBytes) {
			continue
		}
		// Bind to the manifest exactly as the kernel does.
		if manifest == nil || int64(len(artifact)) != manifest.ArtifactSize || sha256Hex(artifact) != manifest.ArtifactSHA256 {
			return nil, urlcatfeed.ErrBinding
		}
		if !bytes.Equal(bundle, m.gens[i].BundleBytes) {
			return nil, urlcatfeed.ErrVerify
		}
		a := m.gens[i].Artifact
		a.Categories = append([]urlcatfeed.ArtifactCategory(nil), m.gens[i].Artifact.Categories...)
		return &a, nil
	}
	return nil, urlcatfeed.ErrVerify
}

// saasFeedCategoriesForTest returns a legacy-syncer category input (a unique test
// category so mergeSaaSCategories side effects on the shared catStore are cleanable).
func saasFeedCategoriesForTest() []saasfeed.Category {
	return []saasfeed.Category{{Name: "f3b3-legacy-test", Hosts: []string{"legacy-probe.example"}}}
}
