// Package bootstrap generates the one-click DP-node deployment artifacts:
// the shell install script and the docker-compose.yml that the Control
// Plane serves against a single-use enrollment token. Extracted from
// package main per ADR-0002 as a pure stdlib leaf: the HTTP handlers (token
// validation against the cluster store, CP address derivation from cluster
// state) stay in main; this package owns the templates, the image-reference
// resolution, and the pure request-derivation helpers — with main's
// trustForwardedHeaders global passed IN as a parameter.
package bootstrap

import (
	"encoding/json"
	"errors"
	"io"
	"net"
	"net/http"
	"os"
	"strings"
	"text/template"
)

// DefaultImage is the default container image; overridden by registry
// settings.
const DefaultImage = "ghcr.io/kidcarmi/culvert"

// registryURL reads the optional registry override from the settings file.
// Returns "" when the file is absent/unreadable/unset (fall back to the
// default image).
func registryURL(settingsPath string) string {
	data, err := os.ReadFile(settingsPath) // #nosec G304 -- operator-configured path
	if err != nil || len(data) == 0 {
		return ""
	}
	var s map[string]string
	if json.Unmarshal(data, &s) != nil {
		return ""
	}
	return s["registry_url"]
}

// tagFor maps the build version to an image tag ("dev" builds pull latest).
func tagFor(version string) string {
	if version != "dev" {
		return version
	}
	return "latest"
}

// Image returns the image reference for DP nodes, checking registry
// settings first, falling back to the default ghcr.io image with the
// current version.
func Image(settingsPath, version string) string {
	if base := registryURL(settingsPath); base != "" {
		// The reference is rendered into the compose document a DP node runs.
		// An override that is not a plain image reference is ignored rather
		// than propagated (SEC-BOOTSTRAP-HOST-1, defence in depth).
		if ref := base + ":" + tagFor(version); SafeImageRef(ref) {
			return ref
		}
	}
	return DefaultImage + ":" + tagFor(version)
}

// ── Bootstrap shell script ─────────────────────────────────────────────────

var scriptTmpl = template.Must(template.New("bootstrap").Parse(`#!/bin/bash
# ─── Culvert Data Plane Bootstrap ────────────────────────────────────────
# Generated by Control Plane at {{.CPHost}}
# This script installs Docker (if needed) and starts a Culvert DP node.
set -euo pipefail

COMPOSE_DIR="/opt/culvert-dp"
CP_BASE='{{.CPBase}}'
TOKEN_PATH='{{.TokenPath}}'

echo "╔══════════════════════════════════════════╗"
echo "║   Culvert Data Plane Bootstrap           ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# ── 1. Install Docker if not present ────────────────────────────────────
install_docker() {
  echo "[1/4] Checking Docker installation..."
  if command -v docker &>/dev/null; then
    echo "  ✓ Docker already installed: $(docker --version)"
  else
    echo "  → Installing Docker Engine..."
    if [ -f /etc/os-release ]; then
      . /etc/os-release
      case "$ID" in
        ubuntu|debian)
          apt-get update -qq
          apt-get install -y -qq ca-certificates curl gnupg lsb-release
          install -m 0755 -d /etc/apt/keyrings
          curl -fsSL "https://download.docker.com/linux/$ID/gpg" | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          chmod a+r /etc/apt/keyrings/docker.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/$ID $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
          apt-get update -qq
          apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
          ;;
        centos|rhel|rocky|alma|fedora)
          dnf install -y dnf-plugins-core || yum install -y yum-utils
          dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo 2>/dev/null || \
            yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          dnf install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin 2>/dev/null || \
            yum install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
          ;;
        amzn)
          yum install -y docker
          # Amazon Linux uses older docker; install compose plugin separately
          mkdir -p /usr/local/lib/docker/cli-plugins
          COMPOSE_VER=$(curl -fsSL https://api.github.com/repos/docker/compose/releases/latest | grep '"tag_name"' | head -1 | cut -d'"' -f4)
          curl -fsSL "https://github.com/docker/compose/releases/download/${COMPOSE_VER}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/lib/docker/cli-plugins/docker-compose
          chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
          ;;
        *)
          echo "  ✗ Unsupported distro: $ID. Install Docker manually: https://docs.docker.com/engine/install/"
          exit 1
          ;;
      esac
    else
      echo "  ✗ Cannot detect OS. Install Docker manually: https://docs.docker.com/engine/install/"
      exit 1
    fi
    systemctl enable --now docker
    echo "  ✓ Docker installed: $(docker --version)"
  fi

  # Verify compose plugin
  if ! docker compose version &>/dev/null; then
    echo "  ✗ Docker Compose plugin not found. Install it: https://docs.docker.com/compose/install/"
    exit 1
  fi
  echo "  ✓ Docker Compose: $(docker compose version --short)"
}

# ── 2. Create working directory ─────────────────────────────────────────
setup_dir() {
  echo ""
  echo "[2/4] Setting up $COMPOSE_DIR..."
  mkdir -p "$COMPOSE_DIR"
  cd "$COMPOSE_DIR"
  echo "  ✓ Working directory ready"
}

# ── 3. Download docker-compose.yml from Control Plane ───────────────────
download_compose() {
  echo ""
  echo "[3/4] Downloading docker-compose.yml from Control Plane..."
  curl -fsSL -k "${CP_BASE}/api/cluster/bootstrap/${TOKEN_PATH}/compose" -o docker-compose.yml
  echo "  ✓ docker-compose.yml downloaded"
}

# ── 4. Start DP node ────────────────────────────────────────────────────
start_dp() {
  echo ""
  echo "[4/4] Starting Culvert Data Plane..."
  docker compose up -d
  echo ""
  echo "  ✓ Data Plane node started!"
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  The DP node is enrolling with the Control Plane."
  echo "  Check status:  cd $COMPOSE_DIR && docker compose logs -f dp"
  echo "  Stop:          cd $COMPOSE_DIR && docker compose down"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
}

# ── Run ─────────────────────────────────────────────────────────────────
install_docker
setup_dir
download_compose
start_dp
`))

// ── Docker Compose template for DP ─────────────────────────────────────

var composeTmpl = template.Must(template.New("compose").Parse(`# Culvert Data Plane — generated by Control Plane
# DO NOT EDIT — managed by the Culvert cluster system
#
# To update: use the Updates panel in the Control Plane GUI
# To stop:   docker compose down
# To logs:   docker compose logs -f dp

services:
  dp:
    image: {{.Image}}
    container_name: culvert-dp
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "1080:1080"
    volumes:
      - dp-data:/data
    environment:
      - TZ=UTC
      - "ENROLL_URL={{.EnrollURL}}"
    command: >
      sh -c '
        ARGS="-port 8080
          -ca-path /data/ca.bundle
          -blocklist /data/blocklist.txt
          -policy /data/policy.json
          -logfile /data/proxy.log
          -audit-log /data/audit.jsonl
          -geoip-db /app/GeoLite2-Country.mmdb
          -yara-rules-dir /data/yara
          -threat-feed-db /data/threatfeeds.json
          -cat-feed-db /data/catfeeddb
          -fileprofiles-file /data/fileprofiles.json
          -idp-profiles-file /data/idp_profiles.json"

        if [ -n "$$ENROLL_URL" ]; then
          ARGS="$$ARGS --enroll $$ENROLL_URL"
        fi

        exec ./culvert $$ARGS
      '
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  dp-data:
`))

// ErrUnsafeArtifactValue is returned when a value handed to a renderer is not
// provably safe to interpolate into a root-executed artifact. It is a refusal,
// never a request to sanitise and continue: callers must abandon the render.
var ErrUnsafeArtifactValue = errors.New("bootstrap: refusing to render an artifact from an unvalidated value")

// RenderScript writes the install script for the given CP host/base and
// enrollment token.
//
// FAIL-CLOSED (SEC-BOOTSTRAP-HOST-1): cpHost/cpBase are derived from request
// headers and token from the URL path, and the output is documented to be piped
// into `sudo bash`. Every one of them is re-validated HERE, at the sink, even
// though the handler validated at the source — the renderer is the last place
// that can still refuse, and it must not depend on a caller having done so. A
// caller that has not validated gets an error and an unwritten stream, never a
// partially-rendered script.
func RenderScript(w io.Writer, cpHost, cpBase, token string) error {
	if _, ok := SafeAuthority(cpHost); !ok {
		return ErrUnsafeArtifactValue
	}
	if !safeBaseURL(cpBase) {
		return ErrUnsafeArtifactValue
	}
	if !SafeToken(token) {
		return ErrUnsafeArtifactValue
	}
	return scriptTmpl.Execute(w, map[string]string{
		"CPHost":    cpHost,
		"CPBase":    cpBase,
		"TokenPath": token,
	})
}

// safeBaseURL reports whether base is exactly "http://<authority>" or
// "https://<authority>" for an authority SafeAuthority accepts. It exists so
// the sink check is over the value that actually reaches the template rather
// than over the parts it was built from.
func safeBaseURL(base string) bool {
	rest, ok := strings.CutPrefix(base, "https://")
	if !ok {
		rest, ok = strings.CutPrefix(base, "http://")
	}
	if !ok {
		return false
	}
	_, valid := SafeAuthority(rest)
	return valid
}

// RenderCompose writes the docker-compose.yml for the given image ref and
// enrollment URL.
//
// FAIL-CLOSED for the same reason RenderScript is (SEC-BOOTSTRAP-HOST-1): the
// enrollment URL carries a request-derived authority and the compose document
// is run by the DP node. Both values are re-validated at the sink.
func RenderCompose(w io.Writer, image, enrollURL string) error {
	if !SafeImageRef(image) {
		return ErrUnsafeArtifactValue
	}
	if !SafeEnrollURL(enrollURL) {
		return ErrUnsafeArtifactValue
	}
	return composeTmpl.Execute(w, map[string]string{
		"Image":     image,
		"EnrollURL": enrollURL,
	})
}

// SafeEnrollURL reports whether u is a culvert:// enrollment URL built from
// values this appliance controls: an authority SafeAuthority accepts, a token
// SafeToken accepts, and a lowercase-hex SHA-256 CA fingerprint.
//
// It parses the shape rather than scanning a charset, because "no dangerous
// byte" is a claim that has to be re-argued every time the sink changes, while
// "this is the URL we build" stays true.
func SafeEnrollURL(u string) bool {
	const scheme = "culvert://enroll/"
	rest, ok := strings.CutPrefix(u, scheme)
	if !ok || len(u) > 512 {
		return false
	}
	addr, rest, ok := strings.Cut(rest, "/")
	if !ok {
		return false
	}
	if _, valid := SafeAuthority(addr); !valid {
		return false
	}
	tok, fp, ok := strings.Cut(rest, "?ca-fp=sha256:")
	if !ok || !SafeToken(tok) {
		return false
	}
	return isLowerHex(fp, 64)
}

// isLowerHex reports whether s is exactly n lowercase hex digits.
func isLowerHex(s string, n int) bool {
	if len(s) != n {
		return false
	}
	for i := 0; i < len(s); i++ {
		c := s[i]
		if (c < '0' || c > '9') && (c < 'a' || c > 'f') {
			return false
		}
	}
	return true
}

// ── Pure request-derivation helpers ─────────────────────────────────────

// ExtractToken extracts the token segment from a bootstrap URL path.
// For /api/cluster/bootstrap/abc123 → "abc123"
// For /api/cluster/bootstrap/abc123/compose → "abc123"
func ExtractToken(path, prefix string) string {
	if !strings.HasPrefix(path, prefix) {
		return ""
	}
	rest := path[len(prefix):]
	// Strip trailing /compose if present
	rest = strings.TrimSuffix(rest, "/compose")
	// Must be a single segment (no slashes)
	if strings.Contains(rest, "/") {
		return ""
	}
	return rest
}

// BaseURL derives the CP's external base URL from the incoming request.
// trustForwarded is main's trustForwardedHeaders setting, passed in so the
// package stays free of main's globals.
// It is FAIL-CLOSED: the derived authority must be a plain host[:port]
// (SafeAuthority). A caller that ignores the second return value and renders
// the first anyway reintroduces SEC-BOOTSTRAP-HOST-1 — see hostsafety.go.
func BaseURL(r *http.Request, trustForwarded bool) (string, bool) {
	scheme := "https"
	if r.TLS == nil {
		scheme = "http"
	}
	host := r.Host
	if trustForwarded {
		if fp := r.Header.Get("X-Forwarded-Proto"); fp == "http" || fp == "https" {
			scheme = fp
		}
		if fh := r.Header.Get("X-Forwarded-Host"); fh != "" {
			host = fh
		}
	}
	safe, ok := SafeAuthority(host)
	if !ok {
		return "", false
	}
	return scheme + "://" + safe, true
}

// EnrollmentAddr derives the gRPC Control Plane address for the enrollment
// URL. Uses the HTTP request's host (the IP/hostname the admin used to
// access the UI) combined with the gRPC port from the configured listen
// address. IPv6-safe: strips brackets before net.JoinHostPort to prevent
// double-bracketing.
// It is FAIL-CLOSED for the same reason BaseURL is: the result is interpolated
// into the compose document a DP node runs (SEC-BOOTSTRAP-HOST-1).
func EnrollmentAddr(r *http.Request, grpcListenAddr string, trustForwarded bool) (string, bool) {
	// If grpcAddr already contains a routable host (not just :port), use it as-is.
	if grpcListenAddr != "" {
		gHost, _, err := net.SplitHostPort(grpcListenAddr)
		if err == nil && gHost != "" && gHost != "0.0.0.0" && gHost != "::" {
			return SafeAuthority(grpcListenAddr)
		}
	}

	// Derive host from the HTTP request.
	cpHost := r.Host
	if trustForwarded {
		if fh := r.Header.Get("X-Forwarded-Host"); fh != "" {
			cpHost = fh
		}
	}

	// Extract host — IPv6-safe (r.Host for IPv6 is [::1]:port).
	host, _, err := net.SplitHostPort(cpHost)
	if err != nil {
		// No port or bare host — strip brackets to prevent [[::1]]:port
		host = strings.Trim(cpHost, "[]")
	}

	// Extract gRPC port from the listen address.
	_, grpcPort, err := net.SplitHostPort(grpcListenAddr)
	if err != nil || grpcPort == "" {
		grpcPort = "50051"
	}

	// net.JoinHostPort adds brackets for IPv6 automatically.
	return SafeAuthority(net.JoinHostPort(host, grpcPort))
}
