// Package bootstrap generates the one-click DP-node deployment artifacts:
// the shell install script and the docker-compose.yml that the Control
// Plane serves against a single-use enrollment token. Extracted from
// package main per ADR-0002 as a pure stdlib leaf: the HTTP handlers (token
// validation against the cluster store, CP address derivation from cluster
// state) stay in main; this package owns the templates, the image-reference
// resolution, and the pure request-derivation helpers — with main's
// trustForwardedHeaders global passed IN as a parameter.
package bootstrap

import (
	"encoding/json"
	"io"
	"net"
	"net/http"
	"os"
	"strings"
	"text/template"
)

// DefaultImage is the default container image; overridden by registry
// settings.
const DefaultImage = "ghcr.io/kidcarmi/culvert"

// registryURL reads the optional registry override from the settings file.
// Returns "" when the file is absent/unreadable/unset (fall back to the
// default image).
func registryURL(settingsPath string) string {
	data, err := os.ReadFile(settingsPath) // #nosec G304 -- operator-configured path
	if err != nil || len(data) == 0 {
		return ""
	}
	var s map[string]string
	if json.Unmarshal(data, &s) != nil {
		return ""
	}
	return s["registry_url"]
}

// tagFor maps the build version to an image tag ("dev" builds pull latest).
func tagFor(version string) string {
	if version != "dev" {
		return version
	}
	return "latest"
}

// Image returns the image reference for DP nodes, checking registry
// settings first, falling back to the default ghcr.io image with the
// current version.
func Image(settingsPath, version string) string {
	if base := registryURL(settingsPath); base != "" {
		return base + ":" + tagFor(version)
	}
	return DefaultImage + ":" + tagFor(version)
}

// ── Bootstrap shell script ─────────────────────────────────────────────────

var scriptTmpl = template.Must(template.New("bootstrap").Parse(`#!/bin/bash
# ─── Culvert Data Plane Bootstrap ────────────────────────────────────────
# Generated by Control Plane at {{.CPHost}}
# This script installs Docker (if needed) and starts a Culvert DP node.
set -euo pipefail

COMPOSE_DIR="/opt/culvert-dp"
CP_BASE="{{.CPBase}}"
TOKEN_PATH="{{.TokenPath}}"

echo "╔══════════════════════════════════════════╗"
echo "║   Culvert Data Plane Bootstrap           ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# ── 1. Install Docker if not present ────────────────────────────────────
install_docker() {
  echo "[1/4] Checking Docker installation..."
  if command -v docker &>/dev/null; then
    echo "  ✓ Docker already installed: $(docker --version)"
  else
    echo "  → Installing Docker Engine..."
    if [ -f /etc/os-release ]; then
      . /etc/os-release
      case "$ID" in
        ubuntu|debian)
          apt-get update -qq
          apt-get install -y -qq ca-certificates curl gnupg lsb-release
          install -m 0755 -d /etc/apt/keyrings
          curl -fsSL "https://download.docker.com/linux/$ID/gpg" | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          chmod a+r /etc/apt/keyrings/docker.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/$ID $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
          apt-get update -qq
          apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
          ;;
        centos|rhel|rocky|alma|fedora)
          dnf install -y dnf-plugins-core || yum install -y yum-utils
          dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo 2>/dev/null || \
            yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          dnf install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin 2>/dev/null || \
            yum install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
          ;;
        amzn)
          yum install -y docker
          # Amazon Linux uses older docker; install compose plugin separately
          mkdir -p /usr/local/lib/docker/cli-plugins
          COMPOSE_VER=$(curl -fsSL https://api.github.com/repos/docker/compose/releases/latest | grep '"tag_name"' | head -1 | cut -d'"' -f4)
          curl -fsSL "https://github.com/docker/compose/releases/download/${COMPOSE_VER}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/lib/docker/cli-plugins/docker-compose
          chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
          ;;
        *)
          echo "  ✗ Unsupported distro: $ID. Install Docker manually: https://docs.docker.com/engine/install/"
          exit 1
          ;;
      esac
    else
      echo "  ✗ Cannot detect OS. Install Docker manually: https://docs.docker.com/engine/install/"
      exit 1
    fi
    systemctl enable --now docker
    echo "  ✓ Docker installed: $(docker --version)"
  fi

  # Verify compose plugin
  if ! docker compose version &>/dev/null; then
    echo "  ✗ Docker Compose plugin not found. Install it: https://docs.docker.com/compose/install/"
    exit 1
  fi
  echo "  ✓ Docker Compose: $(docker compose version --short)"
}

# ── 2. Create working directory ─────────────────────────────────────────
setup_dir() {
  echo ""
  echo "[2/4] Setting up $COMPOSE_DIR..."
  mkdir -p "$COMPOSE_DIR"
  cd "$COMPOSE_DIR"
  echo "  ✓ Working directory ready"
}

# ── 3. Download docker-compose.yml from Control Plane ───────────────────
download_compose() {
  echo ""
  echo "[3/4] Downloading docker-compose.yml from Control Plane..."
  curl -fsSL -k "${CP_BASE}/api/cluster/bootstrap/${TOKEN_PATH}/compose" -o docker-compose.yml
  echo "  ✓ docker-compose.yml downloaded"
}

# ── 4. Start DP node ────────────────────────────────────────────────────
start_dp() {
  echo ""
  echo "[4/4] Starting Culvert Data Plane..."
  docker compose up -d
  echo ""
  echo "  ✓ Data Plane node started!"
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  The DP node is enrolling with the Control Plane."
  echo "  Check status:  cd $COMPOSE_DIR && docker compose logs -f dp"
  echo "  Stop:          cd $COMPOSE_DIR && docker compose down"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
}

# ── Run ─────────────────────────────────────────────────────────────────
install_docker
setup_dir
download_compose
start_dp
`))

// ── Docker Compose template for DP ─────────────────────────────────────

var composeTmpl = template.Must(template.New("compose").Parse(`# Culvert Data Plane — generated by Control Plane
# DO NOT EDIT — managed by the Culvert cluster system
#
# To update: use the Updates panel in the Control Plane GUI
# To stop:   docker compose down
# To logs:   docker compose logs -f dp

services:
  dp:
    image: {{.Image}}
    container_name: culvert-dp
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "1080:1080"
    volumes:
      - dp-data:/data
    environment:
      - TZ=UTC
      - ENROLL_URL={{.EnrollURL}}
    command: >
      sh -c '
        ARGS="-port 8080
          -ca-path /data/ca.bundle
          -blocklist /data/blocklist.txt
          -policy /data/policy.json
          -logfile /data/proxy.log
          -audit-log /data/audit.jsonl
          -geoip-db /app/GeoLite2-Country.mmdb
          -yara-rules-dir /data/yara
          -threat-feed-db /data/threatfeeds.json
          -cat-feed-db /data/catfeeddb
          -fileprofiles-file /data/fileprofiles.json
          -idp-profiles-file /data/idp_profiles.json"

        if [ -n "$$ENROLL_URL" ]; then
          ARGS="$$ARGS --enroll $$ENROLL_URL"
        fi

        exec ./culvert $$ARGS
      '
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  dp-data:
`))

// RenderScript writes the install script for the given CP host/base and
// enrollment token.
func RenderScript(w io.Writer, cpHost, cpBase, token string) error {
	return scriptTmpl.Execute(w, map[string]string{
		"CPHost":    cpHost,
		"CPBase":    cpBase,
		"TokenPath": token,
	})
}

// RenderCompose writes the docker-compose.yml for the given image ref and
// enrollment URL.
func RenderCompose(w io.Writer, image, enrollURL string) error {
	return composeTmpl.Execute(w, map[string]string{
		"Image":     image,
		"EnrollURL": enrollURL,
	})
}

// ── Pure request-derivation helpers ─────────────────────────────────────

// ExtractToken extracts the token segment from a bootstrap URL path.
// For /api/cluster/bootstrap/abc123 → "abc123"
// For /api/cluster/bootstrap/abc123/compose → "abc123"
func ExtractToken(path, prefix string) string {
	if !strings.HasPrefix(path, prefix) {
		return ""
	}
	rest := path[len(prefix):]
	// Strip trailing /compose if present
	rest = strings.TrimSuffix(rest, "/compose")
	// Must be a single segment (no slashes)
	if strings.Contains(rest, "/") {
		return ""
	}
	return rest
}

// BaseURL derives the CP's external base URL from the incoming request.
// trustForwarded is main's trustForwardedHeaders setting, passed in so the
// package stays free of main's globals.
func BaseURL(r *http.Request, trustForwarded bool) string {
	scheme := "https"
	if r.TLS == nil {
		scheme = "http"
	}
	host := r.Host
	if trustForwarded {
		if fp := r.Header.Get("X-Forwarded-Proto"); fp == "http" || fp == "https" {
			scheme = fp
		}
		if fh := r.Header.Get("X-Forwarded-Host"); fh != "" {
			host = fh
		}
	}
	return scheme + "://" + host
}

// EnrollmentAddr derives the gRPC Control Plane address for the enrollment
// URL. Uses the HTTP request's host (the IP/hostname the admin used to
// access the UI) combined with the gRPC port from the configured listen
// address. IPv6-safe: strips brackets before net.JoinHostPort to prevent
// double-bracketing.
func EnrollmentAddr(r *http.Request, grpcListenAddr string, trustForwarded bool) string {
	// If grpcAddr already contains a routable host (not just :port), use it as-is.
	if grpcListenAddr != "" {
		gHost, _, err := net.SplitHostPort(grpcListenAddr)
		if err == nil && gHost != "" && gHost != "0.0.0.0" && gHost != "::" {
			return grpcListenAddr
		}
	}

	// Derive host from the HTTP request.
	cpHost := r.Host
	if trustForwarded {
		if fh := r.Header.Get("X-Forwarded-Host"); fh != "" {
			cpHost = fh
		}
	}

	// Extract host — IPv6-safe (r.Host for IPv6 is [::1]:port).
	host, _, err := net.SplitHostPort(cpHost)
	if err != nil {
		// No port or bare host — strip brackets to prevent [[::1]]:port
		host = strings.Trim(cpHost, "[]")
	}

	// Extract gRPC port from the listen address.
	_, grpcPort, err := net.SplitHostPort(grpcListenAddr)
	if err != nil || grpcPort == "" {
		grpcPort = "50051"
	}

	// net.JoinHostPort adds brackets for IPv6 automatically.
	return net.JoinHostPort(host, grpcPort)
}
