package pac

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// goldenConfig is the canonical fixture exercising every rule kind.
func goldenConfig() Config {
	return Config{
		ProxyHost: "proxy.corp.example",
		ProxyPort: 3128,
		Exclusions: []string{
			"corp.local",
			"*.internal.example",
			"192.0.2.7",
			"10.0.0.0/8",
			"172.16.0.0/12",
		},
	}
}

// ─── Golden output ────────────────────────────────────────────────────────────

// TestCompile_Golden pins the exact generated bytes. Regenerate deliberately
// with UPDATE_PAC_GOLDEN=1 go test ./internal/pac/ — any diff is a compiler
// contract change and requires a CompilerVersion bump review.
func TestCompile_Golden(t *testing.T) {
	cases := []struct {
		name string
		cfg  Config
		addr string
	}{
		{"full", goldenConfig(), "ignored.example:9090"},
		{"minimal", Config{ProxyHost: "p.example", ProxyPort: 8080}, ""},
		{"host_fallback", Config{ProxyPort: 8080}, "fallback.example:9090"},
		{"degenerate_no_host", Config{ProxyPort: 8080}, ""},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			art := CompileConfig(c.cfg, c.addr, 0)
			golden := filepath.Join("testdata", c.name+".pac.golden")
			if os.Getenv("UPDATE_PAC_GOLDEN") == "1" {
				if err := os.MkdirAll("testdata", 0o750); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(golden, []byte(art.JS), 0o600); err != nil {
					t.Fatal(err)
				}
			}
			want, err := os.ReadFile(golden)
			if err != nil {
				t.Fatalf("read golden (regenerate with UPDATE_PAC_GOLDEN=1): %v", err)
			}
			if art.JS != string(want) {
				t.Errorf("compiled PAC diverges from golden %s.\n--- got ---\n%s\n--- want ---\n%s", c.name, art.JS, want)
			}
		})
	}
}

// ─── Determinism ──────────────────────────────────────────────────────────────

func TestCompile_Deterministic(t *testing.T) {
	cfg := goldenConfig()
	first := CompileConfig(cfg, "addr.example:1", 0)
	for i := 0; i < 10; i++ {
		next := CompileConfig(cfg, "addr.example:1", 0)
		if next.JS != first.JS {
			t.Fatalf("iteration %d: compiled bytes differ", i)
		}
		if next.Digest != first.Digest || next.Fingerprint != first.Fingerprint {
			t.Fatalf("iteration %d: digest/fingerprint differ", i)
		}
	}
}

func TestCompile_FingerprintIndependentOfFallbackHost(t *testing.T) {
	cfg := Config{ProxyPort: 8080, Exclusions: []string{"corp.local"}}
	a := CompileConfig(cfg, "host-a.example:9090", 0)
	b := CompileConfig(cfg, "host-b.example:9090", 0)
	if a.Fingerprint != b.Fingerprint {
		t.Error("fingerprint must not depend on the request-derived fallback host")
	}
	if a.Digest == b.Digest {
		t.Error("digest must cover the actual bytes, which differ per fallback host")
	}
	if !a.HostFallback || !b.HostFallback {
		t.Error("HostFallback must be true when ProxyHost is empty")
	}
}

func TestCompile_GeneratedAtExcludedFromHashes(t *testing.T) {
	cfg := goldenConfig()
	a := CompileConfig(cfg, "", 0)
	b := CompileConfig(cfg, "", 0)
	if a.Digest != b.Digest || a.Fingerprint != b.Fingerprint {
		t.Error("timestamps must not leak into digest or fingerprint")
	}
	if strings.Contains(a.JS, a.GeneratedAt.Format("2006")) && a.GeneratedAt.Year() > 2000 {
		// The year alone could legitimately appear in a hostname; check the
		// full timestamp is absent instead.
		if strings.Contains(a.JS, a.GeneratedAt.Format("2006-01-02")) {
			t.Error("generated timestamp must not appear in the JS body")
		}
	}
}

// ─── DNS efficiency ───────────────────────────────────────────────────────────

func TestCompile_SingleDNSResolve(t *testing.T) {
	art := CompileConfig(goldenConfig(), "", 0)
	if got := strings.Count(art.JS, "dnsResolve("); got != 1 {
		t.Errorf("expected exactly 1 dnsResolve call, got %d:\n%s", got, art.JS)
	}
	// Domain rules must appear before the dnsResolve call.
	dnsIdx := strings.Index(art.JS, "dnsResolve(")
	domIdx := strings.Index(art.JS, `"corp.local"`)
	if domIdx == -1 || domIdx > dnsIdx {
		t.Error("domain exclusions must be evaluated before DNS resolution")
	}
	// CIDR exclusions and RFC1918 checks reuse the cached ip variable.
	if strings.Count(art.JS, "isInNet(ip,") != 6 { // loopback + 3×RFC1918 + 2 CIDRs
		t.Errorf("all isInNet checks must reuse the resolved ip:\n%s", art.JS)
	}
}

// ─── Portability contract (ES3 / ASCII) ───────────────────────────────────────

func TestCompile_PortabilityContract(t *testing.T) {
	// Include an IDN exclusion to prove punycoding keeps the output ASCII.
	cfg := goldenConfig()
	cfg.Exclusions = append(cfg.Exclusions, "münchen.example")
	art := CompileConfig(cfg, "", 0)

	for i := 0; i < len(art.JS); i++ {
		if art.JS[i] > 0x7e || (art.JS[i] < 0x20 && art.JS[i] != '\n') {
			t.Fatalf("non-ASCII/control byte 0x%02x at offset %d", art.JS[i], i)
		}
	}
	if strings.HasPrefix(art.JS, "\xef\xbb\xbf") {
		t.Error("PAC must not carry a BOM (breaks WinHTTP JScript)")
	}
	for _, forbidden := range []string{"let ", "const ", "=>", "`", "...", "JSON.", ".indexOf(", ",\n]", ",\n}"} {
		if strings.Contains(art.JS, forbidden) {
			t.Errorf("post-ES3 construct %q in generated PAC", forbidden)
		}
	}
	if !strings.Contains(art.JS, `"xn--mnchen-3ya.example"`) {
		t.Error("IDN exclusion must be emitted as punycode A-label")
	}
}

// ─── Legacy junk tolerance ────────────────────────────────────────────────────

func TestCompile_LegacyJunkDroppedNotFatal(t *testing.T) {
	art := CompileConfig(Config{
		ProxyHost:  "proxy",
		ProxyPort:  8080,
		Exclusions: []string{"good.example", "999.999.0.0/99", "bad host entry"},
	}, "", 0)
	if !strings.Contains(art.JS, `"good.example"`) {
		t.Error("valid entries must survive junk neighbors")
	}
	if strings.Contains(art.JS, "999.999") || strings.Contains(art.JS, "bad host") {
		t.Error("junk entries must not reach the generated JS")
	}
	if len(art.Warnings) == 0 {
		t.Error("dropped junk must surface as artifact warnings")
	}
}

// ─── Chain + degenerate directive ─────────────────────────────────────────────

func TestCompile_ProxyChain(t *testing.T) {
	art := CompileConfig(Config{ProxyHost: "p.example", ProxyPort: 3128}, "", 0)
	if len(art.ProxyChain) != 1 || art.ProxyChain[0] != "PROXY p.example:3128" {
		t.Errorf("ProxyChain = %v", art.ProxyChain)
	}
	if art.HostFallback {
		t.Error("HostFallback must be false when ProxyHost is configured")
	}

	// Degenerate: no configured host, no usable request host → legacy DIRECT.
	deg := CompileConfig(Config{ProxyPort: 8080}, "", 0)
	if len(deg.ProxyChain) != 1 || deg.ProxyChain[0] != "DIRECT" {
		t.Errorf("degenerate ProxyChain = %v", deg.ProxyChain)
	}
	if !strings.Contains(deg.JS, `return "DIRECT";`) {
		t.Error("degenerate terminal must be DIRECT (legacy behavior)")
	}
}

// ─── Size guardrail ───────────────────────────────────────────────────────────

func TestValidateConfig_OutputSizeGuardrail(t *testing.T) {
	// ~6000 entries × ~240 chars ≈ several MB compiled — must reject.
	excl := make([]string, 6000)
	for i := range excl {
		excl[i] = fmt.Sprintf("host%04d.%s.example", i, strings.Repeat("x", 200))
	}
	_, issues := ValidateConfig(Config{ProxyHost: "p.example", Exclusions: excl})
	found := false
	for _, is := range issues {
		if is.Code == IssueOutputTooLarge {
			found = true
		}
	}
	if !found {
		t.Fatalf("expected output_too_large, got %+v", issues)
	}

	// A modest config stays clean.
	_, issues = ValidateConfig(goldenConfig())
	if len(issues) != 0 {
		t.Fatalf("golden config must validate: %+v", issues)
	}
}
