package pac

// compile.go — the deterministic PAC compiler.
//
// Pipeline: Config → NormalizeLenient → compilePAC → Artifact. The same
// Normalized input always produces byte-identical JS: emission order is the
// configured order (post-dedupe), grouped as domain rules before DNS-dependent
// rules, and nothing runtime-dependent (no timestamps, no map iteration) is
// written into the script body.
//
// Generated-JS portability contract (see docs/operator/pac-traffic-steering.md):
// pure ECMAScript 3, 7-bit ASCII, no BOM, no trailing commas — the floor set
// by Windows WinINET/WinHTTP's JScript engine. Only PROXY and DIRECT
// directives are emitted. DNS is resolved at most ONCE per evaluation, after
// every DNS-free rule, and the result is truthiness-tested so null (Chromium,
// Firefox) and "" (Windows Ex API) failures both fall through identically.

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net"
	"strings"
	"time"
)

// CompilerVersion identifies the PAC generator's output contract. Bump on any
// change that alters generated bytes for an unchanged config.
const CompilerVersion = "1"

// Artifact is one compiled PAC file plus its provenance metadata. JS,
// Fingerprint, Digest, and CompilerVersion are deterministic for a given
// (config, fallback host) input; GeneratedAt and Warnings are operational
// metadata excluded from both hashes.
type Artifact struct {
	// JS is the generated FindProxyForURL script.
	JS string
	// Digest is the SHA-256 hex of JS — the HTTP ETag source. It covers the
	// ACTUAL bytes served, including a request-Host-derived proxy host when
	// the fallback is active.
	Digest string
	// Fingerprint is the SHA-256 hex of the canonical normalized config,
	// independent of the request-derived fallback host.
	Fingerprint string
	// CompilerVersion is the generator contract version.
	CompilerVersion string
	// GeneratedAt is when this artifact was built (metadata only; never
	// hashed, so it cannot break determinism).
	GeneratedAt time.Time
	// Warnings carries normalization warnings (dropped legacy junk, dedupes,
	// host-fallback advisory).
	Warnings []ValidationIssue
	// ProxyChain is the effective directive chain, e.g. ["PROXY p:8080"] or
	// ["DIRECT"] in the degenerate no-host case.
	ProxyChain []string
	// HostFallback is true when the proxy hostname was derived from the
	// request's Host header rather than configuration. Fallback-mode
	// responses vary per request host and must not be shared-cached.
	HostFallback bool
}

// CompileConfig validates (leniently) and compiles c. fallbackAddr is the
// request-derived "host[:port]" used when c.ProxyHost is empty; defaultPort
// is the startup-resolved proxy listener port used when c.ProxyPort is zero.
func CompileConfig(c Config, fallbackAddr string, defaultPort int) Artifact {
	n := NormalizeLenient(c)

	port := n.ProxyPort
	if port == 0 {
		if defaultPort > 0 {
			port = defaultPort
		} else {
			port = 8080
		}
	}
	host := n.ProxyHost
	fallback := false
	if host == "" {
		host = hostFromAddr(fallbackAddr)
		fallback = true
	}
	directive := fmt.Sprintf("PROXY %s:%d", host, port)
	if host == "" {
		// Degenerate branch: no configured host AND no usable request host.
		// Legacy behavior (preserved): fail open to DIRECT.
		directive = "DIRECT"
	}

	js := compilePAC(n, directive)
	sum := sha256.Sum256([]byte(js))
	return Artifact{
		JS:              js,
		Digest:          hex.EncodeToString(sum[:]),
		Fingerprint:     fingerprint(n),
		CompilerVersion: CompilerVersion,
		GeneratedAt:     time.Now(),
		Warnings:        n.Warnings,
		ProxyChain:      []string{directive},
		HostFallback:    fallback,
	}
}

// hostFromAddr extracts the bare hostname from a request Host value
// ("host:port", "https://host:port", bare "host"). The port is discarded —
// /proxy.pac is served from the UI/proxy listener, whose port is not the
// proxy port clients must use.
func hostFromAddr(addr string) string {
	addr = strings.TrimPrefix(addr, "https://")
	addr = strings.TrimPrefix(addr, "http://")
	if h, _, err := net.SplitHostPort(addr); err == nil && h != "" {
		return h
	}
	return addr
}

// fingerprint hashes the canonical normalized config (JSON of host, port, and
// canonical exclusion list — deterministic: slice order, no maps).
func fingerprint(n Normalized) string {
	canon := struct {
		Host       string   `json:"host"`
		Port       int      `json:"port"`
		Exclusions []string `json:"exclusions"`
	}{Host: n.ProxyHost, Port: n.ProxyPort, Exclusions: make([]string, 0, len(n.Exclusions))}
	for _, e := range n.Exclusions {
		canon.Exclusions = append(canon.Exclusions, e.Canonical())
	}
	data, _ := json.Marshal(canon) //nolint:errcheck // fixed struct of strings/ints cannot fail
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

// compilePAC emits the FindProxyForURL body for a normalized config and a
// final directive. Emission grouping: hostname hygiene → plain-hostname
// bypass → DNS-free exclusions (domain/wildcard/IP-literal, configured
// order) → single dnsResolve → built-in loopback/RFC1918 bypass → CIDR
// exclusions (configured order) → terminal directive. All pre-terminal rules
// return DIRECT, so grouping DNS-free rules first cannot change any
// evaluation outcome — it only avoids DNS lookups the answer never needed.
func compilePAC(n Normalized, directive string) string {
	var sb strings.Builder
	sb.WriteString("// Culvert proxy auto-config (PAC). Generated file - do not edit.\n")
	fmt.Fprintf(&sb, "// compiler: v%s\n", CompilerVersion)
	fmt.Fprintf(&sb, "// fingerprint: %s\n", fingerprint(n))
	sb.WriteString("function FindProxyForURL(url, host) {\n")
	sb.WriteString("  // Normalize: clients differ on casing and trailing dots.\n")
	sb.WriteString("  host = host.toLowerCase();\n")
	sb.WriteString("  if (host.charAt(host.length - 1) === \".\") {\n")
	sb.WriteString("    host = host.substring(0, host.length - 1);\n")
	sb.WriteString("  }\n")
	sb.WriteString("  // Always bypass for plain (dotless) names\n")
	sb.WriteString("  if (isPlainHostName(host)) return \"DIRECT\";\n")

	writeDomainExclusions(&sb, n.Exclusions)

	sb.WriteString("\n  // DNS-dependent rules: resolve once, tolerate failure\n")
	sb.WriteString("  var ip = dnsResolve(host);\n")
	sb.WriteString("  if (ip) {\n")
	sb.WriteString("    // Loopback and RFC-1918 private ranges - always DIRECT\n")
	sb.WriteString("    if (isInNet(ip, \"127.0.0.0\", \"255.0.0.0\")) return \"DIRECT\";\n")
	sb.WriteString("    if (isInNet(ip, \"10.0.0.0\", \"255.0.0.0\")) return \"DIRECT\";\n")
	sb.WriteString("    if (isInNet(ip, \"172.16.0.0\", \"255.240.0.0\")) return \"DIRECT\";\n")
	sb.WriteString("    if (isInNet(ip, \"192.168.0.0\", \"255.255.0.0\")) return \"DIRECT\";\n")
	writeCIDRExclusions(&sb, n.Exclusions)
	sb.WriteString("  }\n")

	sb.WriteString("\n  // All other traffic routes through the proxy\n")
	fmt.Fprintf(&sb, "  return %q;\n", directive)
	sb.WriteString("}\n")
	return sb.String()
}

// writeDomainExclusions emits the DNS-free exclusion rules in configured
// order: bare domains (exact + subdomains), wildcards (subdomains only), and
// IP literals (exact).
func writeDomainExclusions(sb *strings.Builder, exclusions []NormalizedExclusion) {
	wrote := false
	for i := range exclusions {
		e := &exclusions[i]
		if e.Kind == KindCIDR {
			continue
		}
		if !wrote {
			sb.WriteString("\n  // Custom exclusions - go DIRECT\n")
			wrote = true
		}
		switch e.Kind {
		case KindWildcard:
			fmt.Fprintf(sb, "  if (dnsDomainIs(host, %q)) return \"DIRECT\";\n", "."+e.Host)
		case KindHostLiteral:
			fmt.Fprintf(sb, "  if (host === %q) return \"DIRECT\";\n", e.Host)
		default: // KindDomain
			fmt.Fprintf(sb, "  if (host === %q || dnsDomainIs(host, %q)) return \"DIRECT\";\n", e.Host, "."+e.Host)
		}
	}
}

// writeCIDRExclusions emits the CIDR exclusion rules (inside the `if (ip)`
// block) in configured order.
func writeCIDRExclusions(sb *strings.Builder, exclusions []NormalizedExclusion) {
	wrote := false
	for i := range exclusions {
		e := &exclusions[i]
		if e.Kind != KindCIDR {
			continue
		}
		if !wrote {
			sb.WriteString("    // Custom CIDR exclusions - go DIRECT\n")
			wrote = true
		}
		fmt.Fprintf(sb, "    if (isInNet(ip, %q, %q)) return \"DIRECT\";\n", e.CIDRIP, e.CIDRMask)
	}
}
