# shellcheck shell=bash
# Shared helpers for .github/workflows/appliance-catalog-update-e2e.yml.
# Each workflow step sources this file; the step environment (GITHUB_ENV)
# provides REPO, DATA_DIR, SOCK, STATE_DIR, KEYS, PRIV, E2E_ROOT, ADMIN, HEALTH.
#
# Catalogs are generated by the PRODUCTION generator and lineage carry
# (TestE2ESeedSignedCatalog → generateReleaseCatalog + collectVerifiedPredecessors)
# with a per-run ed25519 key; every catalog a phase publishes is archived under
# $PUBLISHED/<version_id>/ so a later catalog can carry that release
# byte-identical, exactly as the release pipeline carries real releases.

PUBLISHED="$E2E_ROOT/published"
TESTBIN="$E2E_ROOT/culvert.test"
AGENT_KEYRING_SRC="$E2E_ROOT/agent-keyring.json"
LEDGER="$STATE_DIR/release-trust/ledger.json"

# seed <catalog_version> <version_id> <digest> [carried version_id ...]
# SEED_EXPIRES overrides expires_at.
seed() {
  local cv="$1" vid="$2" dig="$3" carry="" v
  shift 3
  for v in "$@"; do carry="${carry:+$carry:}$PUBLISHED/$v"; done
  CULVERT_E2E_SEED_OUT="$DATA_DIR/release_catalog" CULVERT_E2E_SEED_KEYS="$KEYS" \
  CULVERT_E2E_SEED_PRIV="$PRIV" CULVERT_E2E_SEED_AGENT_KEYRING="$AGENT_KEYRING_SRC" \
  CULVERT_E2E_SEED_VERSION="$cv" CULVERT_E2E_SEED_VERSION_ID="$vid" \
  CULVERT_E2E_SEED_IMAGE_REPO="$REPO" CULVERT_E2E_SEED_IMAGE_DIGEST="$dig" \
  CULVERT_E2E_SEED_EXPIRES="${SEED_EXPIRES:-2099-01-01T00:00:00Z}" CULVERT_E2E_SEED_CARRY="$carry" \
    "$TESTBIN" -test.run '^TestE2ESeedSignedCatalog$' -test.count=1 -test.v | grep -E 'carrying|seeded'
  mkdir -p "$PUBLISHED"
  rm -rf "${PUBLISHED:?}/$vid"
  cp -a "$DATA_DIR/release_catalog" "$PUBLISHED/$vid"
  echo "catalog v$cv: $(python3 -c 'import json,sys;print([r["release_id"] for r in json.load(open(sys.argv[1]))["releases"]])' "$DATA_DIR/release_catalog/index.json")"
}

# emit <mode> <running-ref> <out-file> — an agent request body built by the
# REAL planner from the catalog the Control Plane is serving (see
# TestE2EEmitAgentRequest for the modes).
emit() {
  CULVERT_E2E_REQ_CATALOG="$DATA_DIR/release_catalog" CULVERT_E2E_REQ_KEYS="$KEYS" \
  CULVERT_E2E_REQ_REPO="$REPO" CULVERT_E2E_REQ_RUNNING="$2" CULVERT_E2E_REQ_OUT="$3" \
  CULVERT_E2E_REQ_MODE="$1" "$TESTBIN" -test.run '^TestE2EEmitAgentRequest$' -test.count=1 -test.v | grep -E 'wrote'
}

running_ref() {
  local img
  img="$(docker inspect --format '{{.Image}}' culvert-e2e-proxy)"
  docker inspect --format '{{range .RepoDigests}}{{println .}}{{end}}' "$img" | grep "^${REPO}@sha256:" | head -n1 || true
}

wait_health() { # <label>

  for _ in $(seq 1 60); do curl -fsS "$HEALTH/health" >/dev/null 2>&1 && return 0; sleep 2; done
  echo "FATAL $1: /health did not come up"; docker logs culvert-e2e-proxy 2>&1 | tail -100 || true; return 1
}

wait_admin() { # <label>

  for _ in $(seq 1 60); do curl -fsS "$ADMIN/api/releases" >/dev/null 2>&1 && return 0; sleep 2; done
  echo "FATAL $1: admin API did not come up"; return 1
}

reload_catalog() { # restart the CP so it loads the newly seeded catalog
  docker restart culvert-e2e-proxy >/dev/null
  wait_health "$1"; wait_admin "$1"
}

# ledger_entries — number of signed releases the agent's trust ledger holds
# ("absent" before the agent has ever authorized anything).
ledger_entries() {
  if [ -e "$LEDGER" ]; then
    python3 -c 'import json,sys;print(len(json.load(open(sys.argv[1])).get("entries") or []))' "$LEDGER"
  else
    echo absent
  fi
}

agent_last_op() {
  curl -fsS --unix-socket "$SOCK" http://localhost/v1/status \
    | python3 -c 'import sys,json;d=json.load(sys.stdin);print((d.get("lock_held_by") or {}).get("op_id","") or d.get("last_operation_op_id",""))' 2>/dev/null || true
}

# agent_post <path> <body-file> <out-file> — direct agent call as the
# configured peer; prints the HTTP status.
agent_post() {
  curl -sS -o "$3" -w '%{http_code}' --unix-socket "$SOCK" -H 'Content-Type: application/json' \
    -X POST --data-binary "@$2" "http://localhost$1" || true
}

# op_wait <op_id> — drive an agent op to a terminal state; prints the state.
op_wait() {
  local st=""
  for _ in $(seq 1 180); do
    st="$(curl -fsS --unix-socket "$SOCK" "http://localhost/v1/operations/$1" | python3 -c 'import sys,json;print(json.load(sys.stdin).get("state",""))' 2>/dev/null || true)"
    case "$st" in succeeded|failed|cancelled) break ;; esac
    sleep 2
  done
  curl -fsS --unix-socket "$SOCK" "http://localhost/v1/operations/$1/logs" >&2 || true
  echo "$st"
}

# dispatch <out-file> — POST /api/releases/dispatch for the recommended
# channel (the Release Management API an operator uses); prints the status.
dispatch() {
  curl -sS -o "$1" -w '%{http_code}' -H 'Content-Type: application/json' -X POST \
    -d '{"agent":"local","channel":"recommended"}' "$ADMIN/api/releases/dispatch" || true
}

op_from() { # <dispatch-body-file> — op_id from a 202, or the agent's current op
  local op
  op="$(python3 -c 'import sys,json;print(json.load(open(sys.argv[1])).get("op_id",""))' "$1" 2>/dev/null || true)"
  [ -n "$op" ] || op="$(agent_last_op)"
  echo "$op"
}

# start_agent <config> — (re)start the host agent and wait for its socket.
start_agent() {
  if [ -f "$E2E_ROOT/agent.pid" ]; then
    kill "$(cat "$E2E_ROOT/agent.pid")" 2>/dev/null || true
    sleep 2
  fi
  nohup "$AGENT_BIN" -config "$1" >>"$AGENT_LOG" 2>&1 &
  echo "$!" > "$E2E_ROOT/agent.pid"

  for _ in $(seq 1 60); do
    if [ -S "$SOCK" ] && curl -fsS --unix-socket "$SOCK" http://localhost/v1/health >/dev/null 2>&1; then return 0; fi
    sleep 1
  done
  echo "FATAL: agent socket/health did not come up"; cat "$AGENT_LOG" || true; return 1
}
