// Package approval implements the bounded, four-eyes approval state machine that
// PR-9 uses for both operational approvals (from a PR-6 REQUIRE_APPROVAL
// decision) and local policy-publication requests. It is an administrative
// control projection only: approving a request commits a durable PR-8 approval
// event and yields an unforgeable Receipt, but it NEVER executes an upstream
// call, materializes a credential, or publishes a signed CP→DP snapshot. The
// Receipt is evidence a future stage MAY proceed — not an execution.
//
// Every request is bound at creation to an immutable set of facts (tenant,
// capability, decision/candidate digest, and the policy/catalog/registry/
// inspection revisions it was reasoned about). Approval re-verifies that binding
// against the live revisions at decide time, so a request whose underlying state
// changed (a TOCTOU race) is rejected rather than approved against stale facts.
package approval

import "time"

// Kind distinguishes the two request families PR-9 gates.
type Kind uint8

const (
	// KindUnset is the invalid zero value.
	KindUnset Kind = iota
	// KindOperational is an approval for a PR-6 REQUIRE_APPROVAL runtime decision.
	KindOperational
	// KindPublication is an approval to publish a candidate policy into the local
	// capability-scoped PR-6 store.
	KindPublication
)

// String returns a stable label for the kind.
func (k Kind) String() string {
	switch k {
	case KindOperational:
		return "operational"
	case KindPublication:
		return "publication"
	default:
		return "unset"
	}
}

// State is the approval lifecycle state. Terminal states are immutable.
type State uint8

const (
	// StateUnknown is the invalid zero value (fails closed).
	StateUnknown State = iota
	// StatePending is awaiting a four-eyes decision.
	StatePending
	// StateApproved is a terminal grant.
	StateApproved
	// StateRejected is a terminal denial.
	StateRejected
	// StateExpired is a terminal expiry (never approvable again).
	StateExpired
)

// String returns a stable label for the state.
func (s State) String() string {
	switch s {
	case StatePending:
		return "pending"
	case StateApproved:
		return "approved"
	case StateRejected:
		return "rejected"
	case StateExpired:
		return "expired"
	default:
		return "unknown"
	}
}

// terminal reports whether s is a terminal (immutable) state.
func (s State) terminal() bool {
	return s == StateApproved || s == StateRejected || s == StateExpired
}

// PrincipalID is a STABLE authenticated principal identifier. Four-eyes MUST be
// compared on this value, never on a display name or email (which are neither
// stable nor unique).
type PrincipalID string

// ID is an opaque approval identifier. It is not a secret and not a predictable
// counter exposed as a security token; it is generated by the caller (the
// adminapi service) from a safe unpredictable source and only ever compared for
// equality here.
type ID string

// Revisions is the set of live revisions a request's binding is checked against
// at decide time. A mismatch on any bound revision invalidates the request.
type Revisions struct {
	Policy     uint64
	Catalog    uint64
	Registry   uint64
	Inspection uint64
}

// Binding is the immutable set of facts an approval is bound to. It carries only
// safe references and digests — never secrets, raw arguments, or output bodies.
type Binding struct {
	Tenant     string
	Capability string // "gateway" | "management"

	// Operational decision binding.
	DecisionEventID   string
	DecisionDigest    string
	ServerID          string
	ToolFingerprint   string
	Resource          string
	Action            string
	OperationClass    string
	RiskClass         string
	CredentialProfile string
	PowerCeiling      string

	// Publication binding.
	CandidateHash    string
	BaseRevision     uint64
	ProposedRevision uint64
	SimulationDigest string

	// Revision bindings re-checked at decide time (TOCTOU guard).
	Revisions Revisions
}

// Request is an immutable approval request plus its mutable terminal outcome.
// Only the store mutates state, under its lock, after a durable commit.
type Request struct {
	id        ID
	kind      Kind
	requester PrincipalID
	binding   Binding
	created   time.Time
	expiry    time.Time

	state          State
	approver       PrincipalID
	decidedAt      time.Time
	reason         string
	grantedReceipt *Receipt
}

// ID returns the opaque approval identifier.
func (r *Request) ID() ID { return r.id }

// Kind returns the request family.
func (r *Request) Kind() Kind { return r.kind }

// Requester returns the stable principal that created the request.
func (r *Request) Requester() PrincipalID { return r.requester }

// Binding returns a copy of the immutable binding.
func (r *Request) Binding() Binding { return r.binding }

// Tenant returns the bound tenant.
func (r *Request) Tenant() string { return r.binding.Tenant }

// Capability returns the bound capability.
func (r *Request) Capability() string { return r.binding.Capability }

// Created returns the creation time.
func (r *Request) Created() time.Time { return r.created }

// Expiry returns the expiry time.
func (r *Request) Expiry() time.Time { return r.expiry }

// State returns the current lifecycle state.
func (r *Request) State() State { return r.state }

// Approver returns the deciding principal (zero unless terminal).
func (r *Request) Approver() PrincipalID { return r.approver }

// DecidedAt returns the decision time (zero unless terminal).
func (r *Request) DecidedAt() time.Time { return r.decidedAt }

// Reason returns the safe decision reason (set on rejection).
func (r *Request) Reason() string { return r.reason }

// expiredAt reports whether the request has expired as of now.
func (r *Request) expiredAt(now time.Time) bool { return !now.Before(r.expiry) }
