package apicontract

import (
	"bytes"
	"encoding/json"
	"fmt"
	"html"
	"os"
	"sort"
	"strings"

	"github.com/goccy/go-yaml"
)

// BundleJSON converts the YAML contract to canonical, deterministic JSON.
//
// Determinism is load-bearing (Gate 8): the YAML is decoded into a generic map
// and re-encoded with encoding/json, which sorts object keys lexicographically,
// so the same input always yields byte-identical output regardless of authoring
// order. No external tool, no network — pure Go, air-gap safe.
func BundleJSON(specPath string) ([]byte, error) {
	// Validate first so we never bundle a broken contract.
	if _, err := LoadSpec(specPath); err != nil {
		return nil, err
	}
	raw, err := os.ReadFile(specPath)
	if err != nil {
		return nil, err
	}
	var generic any
	if err := yaml.Unmarshal(raw, &generic); err != nil {
		return nil, fmt.Errorf("decode yaml: %w", err)
	}
	generic = normalizeJSON(generic)
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(generic); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// normalizeJSON converts goccy/go-yaml's map[string]any / []any tree into a form
// json.Marshal serializes deterministically (map keys are sorted by encoding/json).
func normalizeJSON(v any) any {
	switch t := v.(type) {
	case map[string]any:
		m := make(map[string]any, len(t))
		for k, val := range t {
			m[k] = normalizeJSON(val)
		}
		return m
	case map[any]any:
		m := make(map[string]any, len(t))
		for k, val := range t {
			m[fmt.Sprintf("%v", k)] = normalizeJSON(val)
		}
		return m
	case []any:
		for i := range t {
			t[i] = normalizeJSON(t[i])
		}
		return t
	default:
		return v
	}
}

// RenderDocsHTML renders the contract to a single, self-contained HTML page for
// offline viewing. It embeds NO external asset — no CDN, no remote fonts, no
// scripts — so it renders under a strict CSP in an air-gapped browser. Output is
// deterministic (operations sorted by tag, then path, then method).
//
// allowedVis filters operations by x-culvert-visibility so a PUBLIC build can
// never leak internal operations (e.g. pass {"public-supported"} for a customer
// build). An empty/nil set renders every documented operation (the admin build).
func RenderDocsHTML(specPath string, allowedVis ...string) ([]byte, error) {
	spec, err := LoadSpec(specPath)
	if err != nil {
		return nil, err
	}
	allow := map[string]bool{}
	for _, v := range allowedVis {
		if v != "" {
			allow[v] = true
		}
	}
	doc := spec.Doc
	title := "Culvert Admin API"
	version := ""
	if doc.Info != nil {
		if doc.Info.Title != "" {
			title = doc.Info.Title
		}
		version = doc.Info.Version
	}

	// Group operations by first tag.
	type opRow struct{ tag, path, method, summary, vis, perm, danger, opid string }
	var rows []opRow
	for _, o := range spec.Ops {
		if len(allow) > 0 && !allow[Ext(o.Op, "x-culvert-visibility")] {
			continue // filtered out of this visibility build (never leak internal ops)
		}
		tag := "untagged"
		if len(o.Op.Tags) > 0 {
			tag = o.Op.Tags[0]
		}
		rows = append(rows, opRow{
			tag: tag, path: o.Path, method: o.Method, summary: o.Op.Summary, opid: o.Op.OperationID,
			vis: Ext(o.Op, "x-culvert-visibility"), perm: Ext(o.Op, "x-culvert-permission"),
			danger: Ext(o.Op, "x-culvert-danger-level"),
		})
	}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].tag != rows[j].tag {
			return rows[i].tag < rows[j].tag
		}
		if rows[i].path != rows[j].path {
			return rows[i].path < rows[j].path
		}
		return rows[i].method < rows[j].method
	})

	var b strings.Builder
	esc := html.EscapeString
	b.WriteString("<!doctype html>\n")
	b.WriteString("<!-- GENERATED by cmd/apibundle from api/openapi/openapi.yaml — DO NOT EDIT. Run `make api-bundle`. -->\n")
	b.WriteString("<html lang=\"en\"><head><meta charset=\"utf-8\">\n")
	b.WriteString("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
	b.WriteString("<title>" + esc(title) + "</title>\n<style>\n")
	b.WriteString("body{font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;margin:0;color:#1a1a1a;background:#fafafa}")
	b.WriteString("header{background:#0b2942;color:#fff;padding:20px 28px}header h1{margin:0;font-size:20px}header .v{opacity:.75;font-size:13px}")
	b.WriteString("main{max-width:960px;margin:0 auto;padding:24px}")
	b.WriteString("h2{margin:28px 0 8px;font-size:16px;border-bottom:2px solid #0b2942;padding-bottom:4px}")
	b.WriteString(".op{background:#fff;border:1px solid #e0e0e0;border-radius:6px;padding:10px 14px;margin:8px 0}")
	b.WriteString(".m{display:inline-block;font-weight:700;font-size:12px;padding:2px 8px;border-radius:4px;color:#fff;margin-right:8px;min-width:52px;text-align:center}")
	b.WriteString(".GET{background:#2b7a2b}.POST{background:#1f6fb2}.PUT{background:#b26a1f}.DELETE{background:#b21f1f}.PATCH{background:#7a2b7a}")
	b.WriteString(".path{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:14px}")
	b.WriteString(".sum{color:#444;margin:4px 0 0 60px;font-size:14px}")
	b.WriteString(".tags{margin:2px 0 0 60px;font-size:12px;color:#666}.tag{display:inline-block;background:#eef;border-radius:3px;padding:1px 6px;margin-right:6px}")
	b.WriteString(".danger-high{color:#b21f1f;font-weight:600}.note{background:#fff8e1;border:1px solid #ffe082;border-radius:6px;padding:10px 14px;margin:16px 0;font-size:13px}")
	b.WriteString("</style></head><body>\n")
	b.WriteString("<header><h1>" + esc(title) + "</h1><div class=\"v\">Contract version " + esc(version) + " — offline, self-contained</div></header>\n<main>\n")
	b.WriteString("<div class=\"note\">Generated from api/openapi/openapi.yaml. This page contains no external assets and makes no network requests. Error responses are <code>text/plain</code> (actual runtime behavior).</div>\n")

	lastTag := ""
	for _, r := range rows {
		if r.tag != lastTag {
			b.WriteString("<h2>" + esc(r.tag) + "</h2>\n")
			lastTag = r.tag
		}
		b.WriteString("<div class=\"op\">")
		b.WriteString("<span class=\"m " + esc(r.method) + "\">" + esc(r.method) + "</span>")
		b.WriteString("<span class=\"path\">" + esc(r.path) + "</span>")
		if r.summary != "" {
			b.WriteString("<div class=\"sum\">" + esc(r.summary) + "</div>")
		}
		b.WriteString("<div class=\"tags\">")
		b.WriteString("<span class=\"tag\">" + esc(r.perm) + "</span>")
		b.WriteString("<span class=\"tag\">" + esc(r.vis) + "</span>")
		if r.danger != "" {
			cls := "tag"
			if r.danger == "high" {
				cls = "tag danger-high"
			}
			b.WriteString("<span class=\"" + cls + "\">danger:" + esc(r.danger) + "</span>")
		}
		b.WriteString("<span class=\"tag\">" + esc(r.opid) + "</span>")
		b.WriteString("</div></div>\n")
	}
	b.WriteString("</main></body></html>\n")
	return []byte(b.String()), nil
}
