package apicontract

// Inventory generation. The API inventory is a GENERATED artifact derived from
// the route-classification manifest (the machine-enforced source of truth), so it
// can never claim coverage the coverage gate has not proven. It is deterministic
// (sorted) and drift-checked by cmd/apibundle -check, exactly like the JSON/HTML.

import (
	"fmt"
	"sort"
	"strings"
)

// RenderInventory produces the deterministic API-inventory markdown from the
// classification manifest. Totals and per-domain counts are computed from the
// manifest rows; nothing is hand-entered.
func RenderInventory(manifestPath string) ([]byte, error) {
	c, err := LoadClassification(manifestPath)
	if err != nil {
		return nil, fmt.Errorf("load classification: %w", err)
	}

	total := len(c.Rows)
	documented := 0
	exempt := 0
	var undoc []ClassRow
	type domStat struct{ entries, documented int }
	domains := map[string]*domStat{}

	for i := range c.Rows {
		r := &c.Rows[i]
		if r.Documented {
			documented++
		}
		if r.Exemption != nil {
			exempt++
		}
		if r.Visibility == "intentionally-undocumented" {
			undoc = append(undoc, *r)
		}
		ds := domains[r.Domain]
		if ds == nil {
			ds = &domStat{}
			domains[r.Domain] = ds
		}
		ds.entries++
		if r.Documented {
			ds.documented++
		}
	}

	sort.Slice(undoc, func(i, j int) bool {
		if undoc[i].Route != undoc[j].Route {
			return undoc[i].Route < undoc[j].Route
		}
		return undoc[i].Method < undoc[j].Method
	})
	domNames := make([]string, 0, len(domains))
	for d := range domains {
		domNames = append(domNames, d)
	}
	sort.Strings(domNames)

	var b strings.Builder
	writeInventoryHeader(&b, total, documented, exempt)
	writeInventoryUndoc(&b, undoc)
	b.WriteString("## By domain\n\n")
	b.WriteString("| Domain | Entries | Documented |\n|---|---|---|\n")
	for _, d := range domNames {
		ds := domains[d]
		fmt.Fprintf(&b, "| %s | %d | %d |\n", d, ds.entries, ds.documented)
	}
	return []byte(b.String()), nil
}

func writeInventoryHeader(b *strings.Builder, total, documented, exempt int) {
	b.WriteString("# API Inventory\n\n")
	b.WriteString("<!-- GENERATED by cmd/apibundle from api/route-classification.yaml — DO NOT EDIT. Run `make api-bundle`. -->\n\n")
	b.WriteString("Authoritative source: `api/route-classification.yaml` (enforced by the route-coverage gate).\n")
	b.WriteString("This file is generated and drift-checked; the totals below are counted from the manifest, not asserted by hand.\n\n")
	fmt.Fprintf(b, "- **Total method-entries:** %d\n", total)
	fmt.Fprintf(b, "- **Documented:** %d\n", documented)
	fmt.Fprintf(b, "- **Exempt:** %d (all `intentionally-undocumented` non-REST surfaces)\n\n", exempt)
}

func writeInventoryUndoc(b *strings.Builder, undoc []ClassRow) {
	b.WriteString("## Intentionally-undocumented (non-REST) surfaces\n\n")
	b.WriteString("| Method | Route | Reason class |\n|---|---|---|\n")
	for i := range undoc {
		r := &undoc[i]
		reason := "intentionally-undocumented"
		if r.Exemption != nil && r.Exemption.SecurityClass != "" {
			reason = r.Exemption.SecurityClass
		}
		fmt.Fprintf(b, "| %s | `%s` | %s |\n", methodDisplay(r.Method), r.Route, reason)
	}
	b.WriteString("\n")
}

func methodDisplay(m string) string {
	if m == "" || m == "*" {
		return "*"
	}
	return m
}
