// FE-1A foundation tests: the committed production bundle satisfies the
// structural CSP invariants (no inline script/style, no external origins, no
// sourcemaps) and the manifest is valid. The bundle scan runs as the exact
// CLI CI executes (scripts/check-dist.mjs) so the test and the gate cannot
// drift apart; the drift gate keeps committed dist identical to a rebuild.
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { expect, it } from "vitest";

// Vitest runs with cwd = the frontend project root (where vite.config.ts is).
const frontendRoot = process.cwd();

it("committed dist passes the generated-bundle security scan", () => {
  const out = execFileSync(
    process.execPath,
    [join(frontendRoot, "scripts", "check-dist.mjs")],
    { encoding: "utf8" },
  );
  expect(out).toContain("check-dist: OK");
});

it("manifest has a hashed entry chunk for the shell", () => {
  const raw = readFileSync(join(frontendRoot, "dist", "manifest.json"), "utf8");
  const manifest: unknown = JSON.parse(raw);
  expect(typeof manifest).toBe("object");
  if (typeof manifest !== "object" || manifest === null) return;
  const values: unknown[] = Object.values(manifest);
  let entryFile: string | undefined;
  for (const v of values) {
    if (
      typeof v === "object" &&
      v !== null &&
      "isEntry" in v &&
      v.isEntry === true &&
      "file" in v &&
      typeof v.file === "string"
    ) {
      entryFile = v.file;
      break;
    }
  }
  expect(entryFile).toMatch(/^assets\/.+-[A-Za-z0-9_-]{8,}\.js$/);
});

it("generated types carry the do-not-edit provenance header", () => {
  const gen = readFileSync(
    join(frontendRoot, "src", "api", "types.gen.ts"),
    "utf8",
  );
  expect(gen).toMatch(/^\/\/ Code generated by openapi-typescript v/);
  expect(gen).toContain("DO NOT EDIT");
  expect(gen).toContain("sha256:");
});
