#!/usr/bin/env bash
# culvert-firstboot — appliance first-boot provisioning (systemd oneshot).
#
# IDEMPOTENT and RECOVERABLE: every step re-checks its own evidence and marks
# completion in /var/lib/culvert-appliance/state/<step>.done. Re-running after
# an interruption (power loss, missing network) resumes at the first undone
# step. Nothing here regenerates an established application secret or key:
# the only writer of /srv/culvert/.env is scripts/install.sh, whose env_put
# never overwrites an existing value, and the Root CA / session key are
# generated by the proxy itself inside the persistent proxy-data volume.
#
# Steps:
#   ovf        read OVF environment (culvert.* keys) → optional static network
#   console    make the 'culvert' console account usable (see below)
#   images     docker load the pre-baked image tars (by content digest)
#   install    run scripts/install.sh non-interactively against the loaded image
#   done       console banner + status
set -euo pipefail

STATE_DIR=/var/lib/culvert-appliance
STATE="$STATE_DIR/state"
MANIFEST="$STATE_DIR/manifest.env"
INSTALL_SH=/opt/culvert-appliance/bin/culvert-install.sh
STACK_DIR=/srv/culvert
LOG=/var/log/culvert-firstboot.log
mkdir -p "$STATE"
exec > >(tee -a "$LOG") 2>&1
log()  { printf '%s culvert-firstboot: %s\n' "$(date -u +%FT%TZ)" "$*"; }
console() { printf '%s\n' "$*" > /dev/console 2>/dev/null || true; }
done_step() { touch "$STATE/$1.done"; log "step $1: done"; }
step_done() { [[ -f "$STATE/$1.done" ]]; }

# shellcheck source=/dev/null
. "$MANIFEST"

# ── OVF environment (vSphere guestinfo transport or ISO transport) ──────────
OVF_ENV_FILE="$STATE_DIR/ovf-env.xml"
read_ovf_env() {
  if command -v vmtoolsd >/dev/null 2>&1; then
    local raw
    raw="$(vmtoolsd --cmd 'info-get guestinfo.ovfEnv' 2>/dev/null || true)"
    if [[ "$raw" == *"<Environment"* ]]; then printf '%s' "$raw" > "$OVF_ENV_FILE"; return 0; fi
  fi
  local dev mnt
  for dev in /dev/sr0 /dev/cdrom; do
    [[ -b "$dev" ]] || continue
    mnt="$(mktemp -d)"
    if mount -o ro "$dev" "$mnt" 2>/dev/null; then
      if [[ -f "$mnt/ovf-env.xml" ]]; then cp "$mnt/ovf-env.xml" "$OVF_ENV_FILE"; umount "$mnt"; rmdir "$mnt"; return 0; fi
      umount "$mnt"
    fi
    rmdir "$mnt"
  done
  return 1
}
ovf_prop() { # key → value ("" when absent)
  [[ -f "$OVF_ENV_FILE" ]] || { echo ""; return 0; }
  python3 - "$OVF_ENV_FILE" "$1" <<'PY'
import sys, xml.etree.ElementTree as ET
try:
    root = ET.parse(sys.argv[1]).getroot()
except ET.ParseError:
    sys.exit(0)
for el in root.iter():
    if el.tag.endswith('}Property') or el.tag == 'Property':
        k = el.get('{http://schemas.dmtf.org/ovf/environment/1}key') or el.get('key')
        if k == sys.argv[2]:
            print(el.get('{http://schemas.dmtf.org/ovf/environment/1}value') or el.get('value') or '')
            break
PY
}

# ── step: ovf (static network from culvert.net.* keys) ──────────────────────
step_ovf() {
  step_done ovf && return 0
  if read_ovf_env; then
    log "OVF environment found"
    local mode addr gw dns search
    mode="$(ovf_prop culvert.net.mode)"; addr="$(ovf_prop culvert.net.address)"
    gw="$(ovf_prop culvert.net.gateway)"; dns="$(ovf_prop culvert.net.dns)"; search="$(ovf_prop culvert.net.search)"
    if [[ "${mode,,}" == "static" ]]; then
      if [[ -n "$addr" && -n "$gw" ]]; then
        log "applying static network from OVF properties ($addr via $gw)"
        /opt/culvert-appliance/bin/culvert-net static "$addr" "$gw" "${dns:-}" "${search:-}" --from-ovf
      else
        log "WARNING: culvert.net.mode=static but address/gateway missing — staying on DHCP"
        console "culvert-firstboot: static network requested without address/gateway; using DHCP"
      fi
    fi
  else
    log "no OVF environment (not a vSphere/VirtualBox OVF import, or no properties set) — DHCP"
  fi
  done_step ovf
}

# ── step: console (per-instance credential, never shipped) ─────────────────
# Priority: cloud-init already applied an OVF/NoCloud `password` or `public-keys`
# → nothing to do. Otherwise, with NEITHER present the operator would be locked
# out of their own appliance, so mint a one-time random console password, force
# a change at first login, and show it ONCE on the VM console (hypervisor
# console access is already privileged). Never written to any file.
step_console() {
  step_done console && return 0
  local shadow keys=0
  shadow="$(getent shadow culvert | cut -d: -f2 || true)"
  [[ -s /home/culvert/.ssh/authorized_keys ]] && keys=1
  if [[ -n "$shadow" && "$shadow" != '!'* && "$shadow" != '*'* ]]; then
    log "console account already has a password (cloud-init/OVF)"
  elif [[ "$keys" -eq 1 ]]; then
    log "SSH key present for 'culvert'; console password stays locked (set one with: sudo passwd culvert)"
  else
    local pw
    # Bounded producer: `tr … < /dev/urandom | head -c 16` runs under
    # pipefail, and head closing the pipe kills tr with SIGPIPE (status 141),
    # which aborted the whole first boot before the password was set (Codex
    # review, PR #1528). 4 KiB of entropy yields ~900 alphabet characters, so
    # tr always finishes before cut reads; the length is then asserted.
    pw="$(head -c 4096 /dev/urandom | tr -dc 'A-HJ-NP-Za-km-z2-9' | cut -c1-16)"
    [[ ${#pw} -eq 16 ]] || { log "ERROR: console password generation produced ${#pw} characters"; return 1; }
    printf 'culvert:%s\n' "$pw" | chpasswd
    passwd -u culvert >/dev/null 2>&1 || true
    chage -d 0 culvert
    console ""
    console "=================================================================="
    console " Culvert appliance: no SSH key or password was supplied at import."
    console " One-time console login:  user 'culvert'  password: $pw"
    console " You must change it at first login. SSH password login is disabled."
    console "=================================================================="
    console ""
    log "minted a one-time console password for 'culvert' (printed on the VM console only)"
  fi
  done_step console
}

# ── step: images (docker load, verified by content digest) ─────────────────
step_images() {
  step_done images && return 0
  systemctl is-active --quiet docker || systemctl start docker
  local tar ref
  for tar in "$STATE_DIR/images/culvert.tar.gz" "$STATE_DIR/images/clamav.tar.gz"; do
    [[ -f "$tar" ]] || { log "ERROR: $tar missing"; return 1; }
    log "docker load $(basename "$tar")"
    docker load -q -i "$tar"
  done
  ref="${APP_IMAGE_REPO}:${APP_IMAGE_TAG}"
  local id
  id="$(docker image inspect "$ref" --format '{{.Id}}')"
  if [[ "$id" != "$APP_IMAGE_INDEX_DIGEST" ]]; then
    # Classic (non-containerd) image store: the ID is the config digest, not the
    # index. Fall back to the amd64 manifest digest check via RepoDigests.
    if ! docker image inspect "$ref" --format '{{json .RepoDigests}}' | grep -q "$APP_IMAGE_INDEX_DIGEST"; then
      log "ERROR: loaded image identity ($id) does not match the manifest pin $APP_IMAGE_INDEX_DIGEST"
      return 1
    fi
  fi
  docker image inspect "${CLAMAV_IMAGE_REPO#docker.io/}:${CLAMAV_IMAGE_TAG}" >/dev/null
  log "images loaded: $ref ($id), ${CLAMAV_IMAGE_REPO}:${CLAMAV_IMAGE_TAG}"
  done_step images
}

# ── step: install (scripts/install.sh, non-interactive) ─────────────────────
# What install.sh does with these inputs (read it; nothing here duplicates it):
#   CULVERT_PROXY_SEED_REF  → tags the ALREADY-LOADED image as culvert/proxy:pinned
#                             (no registry pull; the catalog is not consulted)
#   CULVERT_INSTALL_ASSUME_DOCKER=1 → skip the Docker repo preflight/install
#                             (Docker is pre-baked; added by the integration owner)
#   stdin=/dev/null         → non-interactive: a per-install CA/log passphrase is
#                             auto-generated into /srv/culvert/.env (never overwritten)
#   maintenance agent       → the loaded image keeps its registry digest (containerd
#                             image store), so install.sh's own cosign check gates
#                             the host-root agent exactly as on a quick-start host.
#                             No break-glass trust flag is passed here.
step_install() {
  step_done install && return 0
  log "running install.sh (first run downloads ~250 MB of ClamAV signatures; up to ~6 min)"
  mkdir -p "$STACK_DIR"
  (
    cd /
    export HOME=/root
    export CULVERT_DIR="$STACK_DIR"
    export CULVERT_PROXY_SEED_REF="${APP_IMAGE_REPO}:${APP_IMAGE_TAG}"
    export CULVERT_INSTALL_ASSUME_DOCKER=1
    export CULVERT_INSTALL_CHANNEL="${CULVERT_INSTALL_CHANNEL:-stable}"
    # The appliance contract is default-DENY at first boot (readiness row
    # policy_posture, docs/appliance/first-boot.md); install.sh persists
    # CULVERT_DEFAULT_ACTION only when told to, so say so here (Codex review,
    # PR #1528).
    export CULVERT_INSTALL_DEFAULT_ACTION=deny
    bash "$INSTALL_SH" < /dev/null
  )
  [[ -f "$STACK_DIR/docker-compose.yml" && -f "$STACK_DIR/.env" ]] || { log "ERROR: install.sh did not produce $STACK_DIR"; return 1; }
  chmod 0600 "$STACK_DIR/.env"
  done_step install
}

# ── step: done ──────────────────────────────────────────────────────────────
step_finish() {
  step_done complete && return 0
  /opt/culvert-appliance/bin/culvert-issue-update || true
  console ""
  console "$(/opt/culvert-appliance/bin/culvert-status --brief 2>/dev/null || echo 'Culvert appliance: provisioning complete')"
  console ""
  done_step complete
}

log "start (appliance $(python3 -c 'import json;print(json.load(open("/var/lib/culvert-appliance/build-info.json"))["appliance"]["version"])' 2>/dev/null || echo '?'))"
step_ovf
step_console
step_images
step_install
step_finish
log "complete"
