#!/usr/bin/env bash
# culvert-firstboot — appliance first-boot provisioning (systemd oneshot).
#
# IDEMPOTENT and RECOVERABLE: every step re-checks its own evidence and marks
# completion in $STATE/<step>.done. Re-running after an interruption (power
# loss, missing network) resumes at the first undone step. Nothing here
# regenerates an established application secret or key: the only writer of
# /srv/culvert/.env is scripts/install.sh, whose env_put never overwrites an
# existing value, and the Root CA / session key are generated by the proxy
# itself inside the persistent proxy-data volume.
#
# Steps:
#   ovf        read OVF environment (culvert.* keys) → optional static network
#   console    make the 'culvert' console account usable + the sudo policy
#   images     docker load the pre-baked image tars (by content digest)
#   install    run scripts/install.sh non-interactively against the loaded
#              image, with a per-instance first-admin SETUP TOKEN
#   agent      VERIFY the maintenance agent landed; otherwise record it as a
#              degraded capability (state/agent.pending) — never claim it
#   done       console banner + status
#
# Modes:
#   culvert-firstboot                 the systemd oneshot (all steps)
#   culvert-firstboot --repair-agent  re-run the agent provisioning with the
#                                     same environment the install step used,
#                                     after fixing egress to Sigstore/GitHub
#                                     (owner review, PR #1528: a plain service
#                                     restart cannot reach a step that already
#                                     recorded completion)
#
# Testing: CULVERT_FIRSTBOOT_LIBRARY=1 sources the functions without running
# main; CULVERT_FB_* override the system paths so the decision logic runs in
# a temp root (appliance_firstboot_test.go).
set -euo pipefail

STATE_DIR="${CULVERT_FB_STATE_DIR:-/var/lib/culvert-appliance}"
STATE="$STATE_DIR/state"
MANIFEST="$STATE_DIR/manifest.env"
INSTALL_SH="${CULVERT_FB_INSTALL_SH:-/opt/culvert-appliance/bin/culvert-install.sh}"
STACK_DIR="${CULVERT_FB_STACK_DIR:-/srv/culvert}"
LOG="${CULVERT_FB_LOG:-/var/log/culvert-firstboot.log}"
SUDOERS_DIR="${CULVERT_FB_SUDOERS_DIR:-/etc/sudoers.d}"
MAINT_UNIT="${CULVERT_FB_MAINT_UNIT:-/etc/systemd/system/culvert-maint.service}"
CONSOLE_USER="${CULVERT_FB_CONSOLE_USER:-culvert}"
CONSOLE_HOME="${CULVERT_FB_CONSOLE_HOME:-/home/culvert}"
BIN_DIR="${CULVERT_FB_BIN_DIR:-/opt/culvert-appliance/bin}"
# Sorts AFTER cloud-init's 90-cloud-init-users (which carries the password-
# requiring rule for the same user): sudoers takes the LAST matching entry.
KEYONLY_SUDOERS="$SUDOERS_DIR/95-culvert-keyonly"

log()  { printf '%s culvert-firstboot: %s\n' "$(date -u +%FT%TZ)" "$*"; }
console() { printf '%s\n' "$*" > /dev/console 2>/dev/null || true; }
done_step() { touch "$STATE/$1.done"; log "step $1: done"; }
step_done() { [[ -f "$STATE/$1.done" ]]; }

# ── OVF environment (vSphere guestinfo transport or ISO transport) ──────────
OVF_ENV_FILE="$STATE_DIR/ovf-env.xml"
read_ovf_env() {
  if command -v vmtoolsd >/dev/null 2>&1; then
    local raw
    raw="$(vmtoolsd --cmd 'info-get guestinfo.ovfEnv' 2>/dev/null || true)"
    if [[ "$raw" == *"<Environment"* ]]; then printf '%s' "$raw" > "$OVF_ENV_FILE"; return 0; fi
  fi
  local dev mnt
  for dev in /dev/sr0 /dev/cdrom; do
    [[ -b "$dev" ]] || continue
    mnt="$(mktemp -d)"
    if mount -o ro "$dev" "$mnt" 2>/dev/null; then
      if [[ -f "$mnt/ovf-env.xml" ]]; then cp "$mnt/ovf-env.xml" "$OVF_ENV_FILE"; umount "$mnt"; rmdir "$mnt"; return 0; fi
      umount "$mnt"
    fi
    rmdir "$mnt"
  done
  return 1
}
ovf_prop() { # key → value ("" when absent)
  [[ -f "$OVF_ENV_FILE" ]] || { echo ""; return 0; }
  python3 - "$OVF_ENV_FILE" "$1" <<'PY'
import sys, xml.etree.ElementTree as ET
try:
    root = ET.parse(sys.argv[1]).getroot()
except ET.ParseError:
    sys.exit(0)
for el in root.iter():
    if el.tag.endswith('}Property') or el.tag == 'Property':
        k = el.get('{http://schemas.dmtf.org/ovf/environment/1}key') or el.get('key')
        if k == sys.argv[2]:
            print(el.get('{http://schemas.dmtf.org/ovf/environment/1}value') or el.get('value') or '')
            break
PY
}

# ── step: ovf (static network from culvert.net.* keys) ──────────────────────
step_ovf() {
  step_done ovf && return 0
  if read_ovf_env; then
    log "OVF environment found"
    local mode addr gw dns search
    mode="$(ovf_prop culvert.net.mode)"; addr="$(ovf_prop culvert.net.address)"
    gw="$(ovf_prop culvert.net.gateway)"; dns="$(ovf_prop culvert.net.dns)"; search="$(ovf_prop culvert.net.search)"
    if [[ "${mode,,}" == "static" ]]; then
      if [[ -n "$addr" && -n "$gw" ]]; then
        log "applying static network from OVF properties ($addr via $gw)"
        "$BIN_DIR/culvert-net" static "$addr" "$gw" "${dns:-}" "${search:-}" --from-ovf
      else
        log "WARNING: culvert.net.mode=static but address/gateway missing — staying on DHCP"
        console "culvert-firstboot: static network requested without address/gateway; using DHCP"
      fi
    fi
  else
    log "no OVF environment (not a vSphere/VirtualBox OVF import, or no properties set) — DHCP"
  fi
  done_step ovf
}

# ── step: console (per-instance credential + sudo policy, never shipped) ───
# console_policy SHADOW_FIELD HAS_KEY MINT_STARTED → one of:
#   password   cloud-init/OVF (or a previous run) set a usable password
#   keyonly    an SSH key was supplied and no password exists
#   mint       neither credential exists: mint a one-time console password
#   remint     a previous run started minting but never got to show it
# A field starting with '!' or '*' is a LOCKED/absent password. The order
# matters: a password that exists is honoured whatever the key state; a
# mint that was interrupted before the console print is re-done even though
# the shadow field now carries OUR password — that password was never seen
# by anyone, and chage -d 0 forces a change at first login anyway, so
# replacing it costs nothing and showing it is the whole point.
console_policy() {
  local shadow="$1" keys="$2" minted="$3"
  if [[ -n "$shadow" && "$shadow" != '!'* && "$shadow" != '*'* ]]; then
    if [[ "$minted" -eq 1 ]]; then echo remint; else echo password; fi
  elif [[ "$keys" -eq 1 ]]; then
    echo keyonly
  else
    echo mint
  fi
}

# write_keyonly_sudoers — passwordless sudo for the console user. The SSH
# private key IS the per-instance credential on a key-provisioned appliance
# (the password is locked, SSH refuses passwords); a sudo rule that demands a
# password the operator was never given is a lockout, not a control (owner
# review, PR #1528). Same posture as Ubuntu cloud images' default user.
# Reverted to password-gated sudo with `culvert-sudo-policy require-password`
# once the operator has set one.
write_keyonly_sudoers() {
  local tmp
  tmp="$(mktemp)"
  printf '%s ALL=(ALL:ALL) NOPASSWD: ALL\n' "$CONSOLE_USER" > "$tmp"
  chmod 0440 "$tmp"
  visudo -c -q -f "$tmp" || { rm -f "$tmp"; return 1; }
  install -m 0440 -o root -g root "$tmp" "$KEYONLY_SUDOERS"
  rm -f "$tmp"
}

mint_console_password() {
  # Bounded producer: `tr … < /dev/urandom | head -c 16` runs under
  # pipefail, and head closing the pipe kills tr with SIGPIPE (status 141),
  # which aborted the whole first boot before the password was set (Codex
  # review, PR #1528). 4 KiB of entropy yields ~900 alphabet characters, so
  # tr always finishes before cut reads; the length is then asserted.
  local pw
  pw="$(head -c 4096 /dev/urandom | tr -dc 'A-HJ-NP-Za-km-z2-9' | cut -c1-16)"
  [[ ${#pw} -eq 16 ]] || { log "ERROR: console password generation produced ${#pw} characters"; return 1; }
  printf '%s' "$pw"
}

step_console() {
  step_done console && return 0
  local shadow keys=0 minted=0 policy
  shadow="$(getent shadow "$CONSOLE_USER" | cut -d: -f2 || true)"
  [[ -s "$CONSOLE_HOME/.ssh/authorized_keys" ]] && keys=1
  [[ -f "$STATE/console.minting" ]] && minted=1
  policy="$(console_policy "$shadow" "$keys" "$minted")"
  case "$policy" in
    password)
      log "console account already has a password (cloud-init/OVF); sudo asks for it"
      ;;
    keyonly)
      write_keyonly_sudoers || { log "ERROR: could not install the key-only sudo policy"; return 1; }
      log "SSH key present for '$CONSOLE_USER', no password: passwordless sudo installed ($KEYONLY_SUDOERS); require a password later with: sudo passwd $CONSOLE_USER && sudo culvert-sudo-policy require-password"
      ;;
    mint|remint)
      local pw
      # Durable "minting started" marker BEFORE the password lands, so a
      # kill between chpasswd and the console print re-mints on the next
      # run instead of reading the never-shown password as "already set".
      touch "$STATE/console.minting"
      pw="$(mint_console_password)" || return 1
      printf '%s:%s\n' "$CONSOLE_USER" "$pw" | chpasswd
      passwd -u "$CONSOLE_USER" >/dev/null 2>&1 || true
      chage -d 0 "$CONSOLE_USER"
      console ""
      console "=================================================================="
      console " Culvert appliance: no SSH key or password was supplied at import."
      console " One-time console login:  user '$CONSOLE_USER'  password: $pw"
      console " You must change it at first login. SSH password login is disabled."
      console "=================================================================="
      console ""
      log "minted a one-time console password for '$CONSOLE_USER' (printed on the VM console only${minted:+; re-minted after an interrupted run})"
      rm -f "$STATE/console.minting"
      ;;
  esac
  done_step console
}

# ── step: images (docker load, verified by content digest) ─────────────────
step_images() {
  step_done images && return 0
  systemctl is-active --quiet docker || systemctl start docker
  local tar ref
  for tar in "$STATE_DIR/images/culvert.tar.gz" "$STATE_DIR/images/clamav.tar.gz"; do
    [[ -f "$tar" ]] || { log "ERROR: $tar missing"; return 1; }
    log "docker load $(basename "$tar")"
    docker load -q -i "$tar"
  done
  ref="${APP_IMAGE_REPO}:${APP_IMAGE_TAG}"
  local id
  id="$(docker image inspect "$ref" --format '{{.Id}}')"
  if [[ "$id" != "$APP_IMAGE_INDEX_DIGEST" ]]; then
    # Classic (non-containerd) image store: the ID is the config digest, not the
    # index. Fall back to the amd64 manifest digest check via RepoDigests.
    if ! docker image inspect "$ref" --format '{{json .RepoDigests}}' | grep -q "$APP_IMAGE_INDEX_DIGEST"; then
      log "ERROR: loaded image identity ($id) does not match the manifest pin $APP_IMAGE_INDEX_DIGEST"
      return 1
    fi
  fi
  docker image inspect "${CLAMAV_IMAGE_REPO#docker.io/}:${CLAMAV_IMAGE_TAG}" >/dev/null
  log "images loaded: $ref ($id), ${CLAMAV_IMAGE_REPO}:${CLAMAV_IMAGE_TAG}"
  done_step images
}

# ── setup token (per instance; gates POST /api/setup/complete) ─────────────
# persisted_setup_token → the token install.sh already persisted in the
# stack's .env (an interrupted run keeps the one the console showed), else "".
persisted_setup_token() {
  [[ -f "$STACK_DIR/.env" ]] || { echo ""; return 0; }
  sed -n 's/^CULVERT_SETUP_TOKEN=//p' "$STACK_DIR/.env" | head -n1
}
mint_setup_token() {
  local tok
  tok="$(head -c 4096 /dev/urandom | tr -dc 'a-f0-9' | cut -c1-32)"
  [[ ${#tok} -eq 32 ]] || { log "ERROR: setup token generation produced ${#tok} characters"; return 1; }
  printf '%s' "$tok"
}

# install_env — the environment install.sh runs under, in ONE place so the
# first boot and --repair-agent provision identically (owner review, PR #1528).
# What install.sh does with these inputs (read it; nothing here duplicates it):
#   CULVERT_PROXY_SEED_REF  → tags the ALREADY-LOADED image as culvert/proxy:pinned
#                             (no registry pull; the catalog is not consulted)
#   CULVERT_INSTALL_ASSUME_DOCKER=1 → skip the Docker repo preflight/install
#   stdin=/dev/null         → non-interactive: a per-install CA/log passphrase is
#                             auto-generated into /srv/culvert/.env (never overwritten)
#   CULVERT_INSTALL_DEFAULT_ACTION=deny → the appliance contract is default-DENY
#                             at first boot (readiness row policy_posture)
#   CULVERT_INSTALL_SETUP_TOKEN → per-instance first-admin setup token
#                             (persisted once; env_put never overwrites)
#   maintenance agent       → the loaded image keeps its registry digest (containerd
#                             image store), so install.sh's own cosign check gates
#                             the host-root agent exactly as on a quick-start host.
#                             No break-glass trust flag is passed here.
run_install_sh() {
  local token="$1"
  (
    cd /
    export HOME=/root
    export CULVERT_DIR="$STACK_DIR"
    export CULVERT_PROXY_SEED_REF="${APP_IMAGE_REPO}:${APP_IMAGE_TAG}"
    export CULVERT_INSTALL_ASSUME_DOCKER=1
    export CULVERT_INSTALL_CHANNEL="${CULVERT_INSTALL_CHANNEL:-stable}"
    export CULVERT_INSTALL_DEFAULT_ACTION=deny
    export CULVERT_INSTALL_SETUP_TOKEN="$token"
    bash "$INSTALL_SH" < /dev/null
  )
}

# ── step: install (scripts/install.sh, non-interactive) ─────────────────────
step_install() {
  step_done install && return 0
  log "running install.sh (first run downloads ~250 MB of ClamAV signatures; up to ~6 min)"
  mkdir -p "$STACK_DIR"
  local token
  token="$(persisted_setup_token)"
  [[ -n "$token" ]] || token="$(mint_setup_token)" || return 1
  run_install_sh "$token"
  [[ -f "$STACK_DIR/docker-compose.yml" && -f "$STACK_DIR/.env" ]] || { log "ERROR: install.sh did not produce $STACK_DIR"; return 1; }
  chmod 0600 "$STACK_DIR/.env"
  [[ "$(persisted_setup_token)" == "$token" ]] || { log "ERROR: install.sh did not persist the setup token"; return 1; }
  done_step install
}

# ── step: agent (verify; never claim) ───────────────────────────────────────
# agent_state → installed | missing:<reason>. The unit file is the packaging
# installer's "fully installed" marker (written last); enabled + a runnable
# binary complete the evidence. The unit need not be ACTIVE here — the agent
# starts on its own and a transient start failure is a different fault.
agent_state() {
  if [[ ! -f "$MAINT_UNIT" ]]; then echo "missing:unit_absent"; return 0; fi
  if ! systemctl is-enabled --quiet culvert-maint 2>/dev/null; then echo "missing:unit_not_enabled"; return 0; fi
  if ! command -v culvert-maint >/dev/null 2>&1; then echo "missing:binary_absent"; return 0; fi
  echo installed
}
step_agent() {
  step_done agent && return 0
  local st
  st="$(agent_state)"
  if [[ "$st" == installed ]]; then
    rm -f "$STATE/agent.pending"
    log "maintenance agent installed ($(culvert-maint --version 2>/dev/null || echo 'version unknown'))"
    done_step agent
    return 0
  fi
  # Degraded, recorded, never fatal: the proxy is complete and the agent is
  # day-2 capability (Release Management). install.sh already said WHY in
  # $LOG (cosign/Sigstore unreachable, GitHub unreachable, installer error).
  printf '%s %s\n' "$(date -u +%FT%TZ)" "${st#missing:}" > "$STATE/agent.pending"
  log "WARNING: maintenance agent NOT installed (${st#missing:}); Release Management stays 'Agent unreachable'. Repair after fixing egress with: sudo culvert-firstboot --repair-agent"
  console "culvert-firstboot: maintenance agent not installed (${st#missing:}) — see culvert-status; repair: sudo culvert-firstboot --repair-agent"
  return 0
}

# repair_agent — the explicit retry path. Re-runs install.sh with EXACTLY the
# first boot's environment (install.sh is idempotent: stack untouched, .env
# values never overwritten, agent (re)installed through its trust gate), then
# re-verifies and clears the pending record only on evidence.
repair_agent() {
  step_done install || { log "ERROR: the install step has not completed; run the first boot (systemctl restart culvert-firstboot) first"; return 1; }
  local token
  token="$(persisted_setup_token)"
  log "repair-agent: re-running install.sh"
  run_install_sh "$token"
  rm -f "$STATE/agent.done"
  step_agent
  if step_done agent; then
    log "repair-agent: maintenance agent installed"
    "$BIN_DIR/culvert-issue-update" >/dev/null 2>&1 || true
    return 0
  fi
  log "repair-agent: still not installed — see $LOG for install.sh's trust-gate output"
  return 1
}

# ── step: done ──────────────────────────────────────────────────────────────
step_finish() {
  step_done complete && return 0
  "$BIN_DIR/culvert-issue-update" || true
  console ""
  console "$("$BIN_DIR/culvert-status" --brief 2>/dev/null || echo 'Culvert appliance: provisioning complete')"
  local token
  token="$(persisted_setup_token)"
  if [[ -n "$token" ]]; then
    console ""
    console " First-admin SETUP TOKEN (required once by the setup wizard at https://<address>:9090):"
    console "   $token"
    console " Also shown by: sudo culvert-status   (root only; it lives in $STACK_DIR/.env)"
    console ""
  fi
  done_step complete
}

main() {
  mkdir -p "$STATE"
  exec > >(tee -a "$LOG") 2>&1
  # shellcheck source=/dev/null
  . "$MANIFEST"
  case "${1:-}" in
    --repair-agent) repair_agent; exit $? ;;
    "") ;;
    *) echo "usage: culvert-firstboot [--repair-agent]" >&2; exit 2 ;;
  esac
  log "start (appliance $(python3 -c 'import json;print(json.load(open("'"$STATE_DIR"'/build-info.json"))["appliance"]["version"])' 2>/dev/null || echo '?'))"
  step_ovf
  step_console
  step_images
  step_install
  step_agent
  step_finish
  log "complete"
}

if [[ "${CULVERT_FIRSTBOOT_LIBRARY:-0}" != 1 ]]; then
  main "$@"
fi
